/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterV2Spec } from './ClusterV2Spec';
import {
    ClusterV2SpecFromJSON,
    ClusterV2SpecFromJSONTyped,
    ClusterV2SpecToJSON,
} from './ClusterV2Spec';
import type { ClusterV2Status } from './ClusterV2Status';
import {
    ClusterV2StatusFromJSON,
    ClusterV2StatusFromJSONTyped,
    ClusterV2StatusToJSON,
} from './ClusterV2Status';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';

/**
 * A compute cluster.
 * @export
 * @interface ClusterV2Read
 */
export interface ClusterV2Read {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof ClusterV2Read
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {ClusterV2Spec}
     * @memberof ClusterV2Read
     */
    spec: ClusterV2Spec;
    /**
     * 
     * @type {ClusterV2Status}
     * @memberof ClusterV2Read
     */
    status: ClusterV2Status;
}

/**
 * Check if a given object implements the ClusterV2Read interface.
 */
export function instanceOfClusterV2Read(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ClusterV2ReadFromJSON(json: any): ClusterV2Read {
    return ClusterV2ReadFromJSONTyped(json, false);
}

export function ClusterV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterV2Read {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': ClusterV2SpecFromJSON(json['spec']),
        'status': ClusterV2StatusFromJSON(json['status']),
    };
}

export function ClusterV2ReadToJSON(value?: ClusterV2Read | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': ClusterV2SpecToJSON(value.spec),
        'status': ClusterV2StatusToJSON(value.status),
    };
}

