/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Console output
 * @export
 * @interface ConsoleOutput
 */
export interface ConsoleOutput {
    /**
     * Console output.
     * @type {string}
     * @memberof ConsoleOutput
     */
    contents: string;
}

/**
 * Check if a given object implements the ConsoleOutput interface.
 */
export function instanceOfConsoleOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function ConsoleOutputFromJSON(json: any): ConsoleOutput {
    return ConsoleOutputFromJSONTyped(json, false);
}

export function ConsoleOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': json['contents'],
    };
}

export function ConsoleOutputToJSON(value?: ConsoleOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': value.contents,
    };
}

