/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceNetworking } from './InstanceNetworking';
import {
    InstanceNetworkingFromJSON,
    InstanceNetworkingFromJSONTyped,
    InstanceNetworkingToJSON,
} from './InstanceNetworking';

/**
 * A compute instance.
 * @export
 * @interface InstanceSpec
 */
export interface InstanceSpec {
    /**
     * The flavor CPU/RAM of a compute instance.
     * @type {string}
     * @memberof InstanceSpec
     */
    flavorId: string;
    /**
     * The image of a compute instance.
     * @type {string}
     * @memberof InstanceSpec
     */
    imageId: string;
    /**
     * 
     * @type {InstanceNetworking}
     * @memberof InstanceSpec
     */
    networking?: InstanceNetworking;
    /**
     * Contains base64-encoded configuration information or scripts to use upon launch.
     * The format of the data is governed by the cloud-init standard, and may be a script,
     * a MIME multipart archive, etc.
     * @type {string}
     * @memberof InstanceSpec
     */
    userData?: string;
}

/**
 * Check if a given object implements the InstanceSpec interface.
 */
export function instanceOfInstanceSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "flavorId" in value;
    isInstance = isInstance && "imageId" in value;

    return isInstance;
}

export function InstanceSpecFromJSON(json: any): InstanceSpec {
    return InstanceSpecFromJSONTyped(json, false);
}

export function InstanceSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flavorId': json['flavorId'],
        'imageId': json['imageId'],
        'networking': !exists(json, 'networking') ? undefined : InstanceNetworkingFromJSON(json['networking']),
        'userData': !exists(json, 'userData') ? undefined : json['userData'],
    };
}

export function InstanceSpecToJSON(value?: InstanceSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flavorId': value.flavorId,
        'imageId': value.imageId,
        'networking': InstanceNetworkingToJSON(value.networking),
        'userData': value.userData,
    };
}

