/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute instances.
 *
 * The version of the OpenAPI document: 1.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceProvisioningStatus } from './ResourceProvisioningStatus';
import {
    ResourceProvisioningStatusFromJSON,
    ResourceProvisioningStatusFromJSONTyped,
    ResourceProvisioningStatusToJSON,
} from './ResourceProvisioningStatus';

/**
 * Observed attachment state for a Volume associated with an Instance.
 * @export
 * @interface InstanceVolumeStatus
 */
export interface InstanceVolumeStatus {
    /**
     * A Region volume ID.
     * @type {string}
     * @memberof InstanceVolumeStatus
     */
    id: string;
    /**
     *
     * @type {ResourceProvisioningStatus}
     * @memberof InstanceVolumeStatus
     */
    provisioningStatus: ResourceProvisioningStatus;
    /**
     * The provider-assigned guest device name, when available.
     * @type {string}
     * @memberof InstanceVolumeStatus
     */
    device?: string;
    /**
     * Optional API-safe description of the attachment state.
     * @type {string}
     * @memberof InstanceVolumeStatus
     */
    message?: string;
}

/**
 * Check if a given object implements the InstanceVolumeStatus interface.
 */
export function instanceOfInstanceVolumeStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "provisioningStatus" in value;

    return isInstance;
}

export function InstanceVolumeStatusFromJSON(json: any): InstanceVolumeStatus {
    return InstanceVolumeStatusFromJSONTyped(json, false);
}

export function InstanceVolumeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceVolumeStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'provisioningStatus': ResourceProvisioningStatusFromJSON(json['provisioningStatus']),
        'device': !exists(json, 'device') ? undefined : json['device'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InstanceVolumeStatusToJSON(value?: InstanceVolumeStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'provisioningStatus': ResourceProvisioningStatusToJSON(value.provisioningStatus),
        'device': value.device,
        'message': value.message,
    };
}
