/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceLifecyclePhase } from './InstanceLifecyclePhase';
import {
    InstanceLifecyclePhaseFromJSON,
    InstanceLifecyclePhaseFromJSONTyped,
    InstanceLifecyclePhaseToJSON,
} from './InstanceLifecyclePhase';

/**
 * Read only status information about a compute instance.
 * @export
 * @interface InstanceStatus
 */
export interface InstanceStatus {
    /**
     * The region a security group belongs to.
     * @type {string}
     * @memberof InstanceStatus
     */
    regionId: string;
    /**
     * The network a security group belongs to.
     * @type {string}
     * @memberof InstanceStatus
     */
    networkId: string;
    /**
     * 
     * @type {InstanceLifecyclePhase}
     * @memberof InstanceStatus
     */
    powerState?: InstanceLifecyclePhase;
    /**
     * The private IP address of the server.
     * @type {string}
     * @memberof InstanceStatus
     */
    privateIP?: string;
    /**
     * The public IP address of the server.
     * @type {string}
     * @memberof InstanceStatus
     */
    publicIP?: string;
}

/**
 * Check if a given object implements the InstanceStatus interface.
 */
export function instanceOfInstanceStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function InstanceStatusFromJSON(json: any): InstanceStatus {
    return InstanceStatusFromJSONTyped(json, false);
}

export function InstanceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
        'networkId': json['networkId'],
        'powerState': !exists(json, 'powerState') ? undefined : InstanceLifecyclePhaseFromJSON(json['powerState']),
        'privateIP': !exists(json, 'privateIP') ? undefined : json['privateIP'],
        'publicIP': !exists(json, 'publicIP') ? undefined : json['publicIP'],
    };
}

export function InstanceStatusToJSON(value?: InstanceStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
        'networkId': value.networkId,
        'powerState': InstanceLifecyclePhaseToJSON(value.powerState),
        'privateIP': value.privateIP,
        'publicIP': value.publicIP,
    };
}

