/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceSpec } from './InstanceSpec';
import {
    InstanceSpecFromJSON,
    InstanceSpecFromJSONTyped,
    InstanceSpecToJSON,
} from './InstanceSpec';
import type { InstanceStatus } from './InstanceStatus';
import {
    InstanceStatusFromJSON,
    InstanceStatusFromJSONTyped,
    InstanceStatusToJSON,
} from './InstanceStatus';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';

/**
 * A compute instance.
 * @export
 * @interface InstanceRead
 */
export interface InstanceRead {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof InstanceRead
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {InstanceSpec}
     * @memberof InstanceRead
     */
    spec: InstanceSpec;
    /**
     * 
     * @type {InstanceStatus}
     * @memberof InstanceRead
     */
    status: InstanceStatus;
}

/**
 * Check if a given object implements the InstanceRead interface.
 */
export function instanceOfInstanceRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function InstanceReadFromJSON(json: any): InstanceRead {
    return InstanceReadFromJSONTyped(json, false);
}

export function InstanceReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': InstanceSpecFromJSON(json['spec']),
        'status': InstanceStatusFromJSON(json['status']),
    };
}

export function InstanceReadToJSON(value?: InstanceRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': InstanceSpecToJSON(value.spec),
        'status': InstanceStatusToJSON(value.status),
    };
}

