/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceCreateSpec } from './InstanceCreateSpec';
import {
    InstanceCreateSpecFromJSON,
    InstanceCreateSpecFromJSONTyped,
    InstanceCreateSpecToJSON,
} from './InstanceCreateSpec';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A compute instance creation request.
 * @export
 * @interface InstanceCreate
 */
export interface InstanceCreate {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof InstanceCreate
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {InstanceCreateSpec}
     * @memberof InstanceCreate
     */
    spec: InstanceCreateSpec;
}

/**
 * Check if a given object implements the InstanceCreate interface.
 */
export function instanceOfInstanceCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function InstanceCreateFromJSON(json: any): InstanceCreate {
    return InstanceCreateFromJSONTyped(json, false);
}

export function InstanceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': InstanceCreateSpecFromJSON(json['spec']),
    };
}

export function InstanceCreateToJSON(value?: InstanceCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': InstanceCreateSpecToJSON(value.spec),
    };
}

