/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A compute instance's network  configuration.
 * @export
 * @interface InstanceNetworking
 */
export interface InstanceNetworking {
    /**
     * A list of security group IDs.
     * @type {Array<string>}
     * @memberof InstanceNetworking
     */
    securityGroups?: Array<string>;
    /**
     * Whether or not to provision a public IP.
     * @type {boolean}
     * @memberof InstanceNetworking
     */
    publicIP?: boolean;
    /**
     * A list of network prefixes that are allowed to egress from the server.
     * By default, only packets from the server's network interface's IP address
     * are allowed to enter the network.  Use of this option allows the server
     * to act as a router without SNAT rules.
     * @type {Array<string>}
     * @memberof InstanceNetworking
     */
    allowedSourceAddresses?: Array<string>;
}

/**
 * Check if a given object implements the InstanceNetworking interface.
 */
export function instanceOfInstanceNetworking(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InstanceNetworkingFromJSON(json: any): InstanceNetworking {
    return InstanceNetworkingFromJSONTyped(json, false);
}

export function InstanceNetworkingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceNetworking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'securityGroups': !exists(json, 'securityGroups') ? undefined : json['securityGroups'],
        'publicIP': !exists(json, 'publicIP') ? undefined : json['publicIP'],
        'allowedSourceAddresses': !exists(json, 'allowedSourceAddresses') ? undefined : json['allowedSourceAddresses'],
    };
}

export function InstanceNetworkingToJSON(value?: InstanceNetworking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'securityGroups': value.securityGroups,
        'publicIP': value.publicIP,
        'allowedSourceAddresses': value.allowedSourceAddresses,
    };
}

