/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceNetworking } from './InstanceNetworking';
import {
    InstanceNetworkingFromJSON,
    InstanceNetworkingFromJSONTyped,
    InstanceNetworkingToJSON,
} from './InstanceNetworking';

/**
 * A compute instance.
 * @export
 * @interface InstanceCreateSpec
 */
export interface InstanceCreateSpec {
    /**
     * The flavor CPU/RAM of a compute instance.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    flavorId: string;
    /**
     * The image of a compute instance.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    imageId: string;
    /**
     * 
     * @type {InstanceNetworking}
     * @memberof InstanceCreateSpec
     */
    networking?: InstanceNetworking;
    /**
     * Contains base64-encoded configuration information or scripts to use upon launch.
     * The format of the data is governed by the cloud-init standard, and may be a script,
     * a MIME multipart archive, etc.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    userData?: string;
    /**
     * The organization to provision the resource in.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    organizationId: string;
    /**
     * The project to provision the resource in.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    projectId: string;
    /**
     * The network ID to attach the compute instance to.
     * @type {string}
     * @memberof InstanceCreateSpec
     */
    networkId: string;
}

/**
 * Check if a given object implements the InstanceCreateSpec interface.
 */
export function instanceOfInstanceCreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "flavorId" in value;
    isInstance = isInstance && "imageId" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function InstanceCreateSpecFromJSON(json: any): InstanceCreateSpec {
    return InstanceCreateSpecFromJSONTyped(json, false);
}

export function InstanceCreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceCreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flavorId': json['flavorId'],
        'imageId': json['imageId'],
        'networking': !exists(json, 'networking') ? undefined : InstanceNetworkingFromJSON(json['networking']),
        'userData': !exists(json, 'userData') ? undefined : json['userData'],
        'organizationId': json['organizationId'],
        'projectId': json['projectId'],
        'networkId': json['networkId'],
    };
}

export function InstanceCreateSpecToJSON(value?: InstanceCreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flavorId': value.flavorId,
        'imageId': value.imageId,
        'networking': InstanceNetworkingToJSON(value.networking),
        'userData': value.userData,
        'organizationId': value.organizationId,
        'projectId': value.projectId,
        'networkId': value.networkId,
    };
}

