/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A workload pool.
 * @export
 * @interface PoolV2Status
 */
export interface PoolV2Status {
    /**
     * The name of the pool.
     * @type {string}
     * @memberof PoolV2Status
     */
    name: string;
    /**
     * The number of instances that exist.
     * @type {number}
     * @memberof PoolV2Status
     */
    replicas: number;
}

/**
 * Check if a given object implements the PoolV2Status interface.
 */
export function instanceOfPoolV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "replicas" in value;

    return isInstance;
}

export function PoolV2StatusFromJSON(json: any): PoolV2Status {
    return PoolV2StatusFromJSONTyped(json, false);
}

export function PoolV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'replicas': json['replicas'],
    };
}

export function PoolV2StatusToJSON(value?: PoolV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'replicas': value.replicas,
    };
}

