/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Acl,
  AllocationRead,
  AllocationWrite,
  AuthorizationRequestOptions,
  JsonWebKeySet,
  LoginRequestOptions,
  ModelError,
  Oauth2Error,
  Oauth2ProviderRead,
  Oauth2ProviderWrite,
  OnboardRequestOptions,
  OpenidConfiguration,
  OpenidProtectedResource,
  OrganizationRead,
  OrganizationWrite,
  QuotasRead,
  QuotasWrite,
  Token,
  TokenRequestOptions,
  Userinfo,
  UserinfoRequestOptions,
} from '../models/index';
import {
    AclFromJSON,
    AclToJSON,
    AllocationReadFromJSON,
    AllocationReadToJSON,
    AllocationWriteFromJSON,
    AllocationWriteToJSON,
    AuthorizationRequestOptionsFromJSON,
    AuthorizationRequestOptionsToJSON,
    JsonWebKeySetFromJSON,
    JsonWebKeySetToJSON,
    LoginRequestOptionsFromJSON,
    LoginRequestOptionsToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
    Oauth2ErrorFromJSON,
    Oauth2ErrorToJSON,
    Oauth2ProviderReadFromJSON,
    Oauth2ProviderReadToJSON,
    Oauth2ProviderWriteFromJSON,
    Oauth2ProviderWriteToJSON,
    OnboardRequestOptionsFromJSON,
    OnboardRequestOptionsToJSON,
    OpenidConfigurationFromJSON,
    OpenidConfigurationToJSON,
    OpenidProtectedResourceFromJSON,
    OpenidProtectedResourceToJSON,
    OrganizationReadFromJSON,
    OrganizationReadToJSON,
    OrganizationWriteFromJSON,
    OrganizationWriteToJSON,
    QuotasReadFromJSON,
    QuotasReadToJSON,
    QuotasWriteFromJSON,
    QuotasWriteToJSON,
    TokenFromJSON,
    TokenToJSON,
    TokenRequestOptionsFromJSON,
    TokenRequestOptionsToJSON,
    UserinfoFromJSON,
    UserinfoToJSON,
    UserinfoRequestOptionsFromJSON,
    UserinfoRequestOptionsToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDAclGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDDeleteRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDOauth2providersGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDOauth2providersPostRequest {
    organizationID: string;
    oauth2ProviderWrite: Oauth2ProviderWrite;
}

export interface ApiV1OrganizationsOrganizationIDOauth2providersProviderIDDeleteRequest {
    organizationID: string;
    providerID: string;
}

export interface ApiV1OrganizationsOrganizationIDOauth2providersProviderIDPutRequest {
    organizationID: string;
    providerID: string;
    oauth2ProviderWrite: Oauth2ProviderWrite;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDeleteRequest {
    organizationID: string;
    projectID: string;
    allocationID: string;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGetRequest {
    organizationID: string;
    projectID: string;
    allocationID: string;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPutRequest {
    organizationID: string;
    projectID: string;
    allocationID: string;
    allocationWrite: AllocationWrite;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPostRequest {
    organizationID: string;
    projectID: string;
    allocationWrite: AllocationWrite;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDeleteRequest {
    organizationID: string;
    projectID: string;
    reference: string;
}

export interface ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePutRequest {
    organizationID: string;
    projectID: string;
    reference: string;
}

export interface ApiV1OrganizationsOrganizationIDQuotasPutRequest {
    organizationID: string;
    quotasWrite: QuotasWrite;
}

export interface ApiV1OrganizationsPostRequest {
    organizationWrite: OrganizationWrite;
}

export interface Oauth2V2AuthorizationPostRequest {
    authorizationRequestOptions: AuthorizationRequestOptions;
}

export interface Oauth2V2LoginPostRequest {
    loginRequestOptions: LoginRequestOptions;
}

export interface Oauth2V2OnboardPostRequest {
    onboardRequestOptions: OnboardRequestOptions;
}

export interface Oauth2V2TokenPostRequest {
    tokenRequestOptions: TokenRequestOptions;
}

export interface Oauth2V2UserinfoPostRequest {
    userinfoRequestOptions?: UserinfoRequestOptions;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns access control properties for the user.
     */
    async apiV1AclGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Acl>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/acl`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AclFromJSON(jsonValue));
    }

    /**
     * Returns access control properties for the user.
     */
    async apiV1AclGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Acl> {
        const response = await this.apiV1AclGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lists system identity providers.
     */
    async apiV1Oauth2providersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Oauth2ProviderRead>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/oauth2providers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(Oauth2ProviderReadFromJSON));
    }

    /**
     * Lists system identity providers.
     */
    async apiV1Oauth2providersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Oauth2ProviderRead>> {
        const response = await this.apiV1Oauth2providersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns access control properties for the user.
     */
    async apiV1OrganizationsOrganizationIDAclGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDAclGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Acl>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDAclGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/acl`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AclFromJSON(jsonValue));
    }

    /**
     * Returns access control properties for the user.
     */
    async apiV1OrganizationsOrganizationIDAclGet(requestParameters: ApiV1OrganizationsOrganizationIDAclGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Acl> {
        const response = await this.apiV1OrganizationsOrganizationIDAclGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an organization, all of its users, groups, projects, and infrastructure.
     */
    async apiV1OrganizationsOrganizationIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an organization, all of its users, groups, projects, and infrastructure.
     */
    async apiV1OrganizationsOrganizationIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Lists an organization\'s identity providers.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Oauth2ProviderRead>>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/oauth2providers`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(Oauth2ProviderReadFromJSON));
    }

    /**
     * Lists an organization\'s identity providers.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersGet(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Oauth2ProviderRead>> {
        const response = await this.apiV1OrganizationsOrganizationIDOauth2providersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2ProviderRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersPost.');
        }

        if (requestParameters.oauth2ProviderWrite === null || requestParameters.oauth2ProviderWrite === undefined) {
            throw new runtime.RequiredError('oauth2ProviderWrite','Required parameter requestParameters.oauth2ProviderWrite was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/oauth2providers`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: Oauth2ProviderWriteToJSON(requestParameters.oauth2ProviderWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2ProviderReadFromJSON(jsonValue));
    }

    /**
     * Create an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersPost(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2ProviderRead> {
        const response = await this.apiV1OrganizationsOrganizationIDOauth2providersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersProviderIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersProviderIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersProviderIDDelete.');
        }

        if (requestParameters.providerID === null || requestParameters.providerID === undefined) {
            throw new runtime.RequiredError('providerID','Required parameter requestParameters.providerID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersProviderIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/oauth2providers/{providerID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"providerID"}}`, encodeURIComponent(String(requestParameters.providerID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersProviderIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersProviderIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDOauth2providersProviderIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersProviderIDPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersProviderIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersProviderIDPut.');
        }

        if (requestParameters.providerID === null || requestParameters.providerID === undefined) {
            throw new runtime.RequiredError('providerID','Required parameter requestParameters.providerID was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersProviderIDPut.');
        }

        if (requestParameters.oauth2ProviderWrite === null || requestParameters.oauth2ProviderWrite === undefined) {
            throw new runtime.RequiredError('oauth2ProviderWrite','Required parameter requestParameters.oauth2ProviderWrite was null or undefined when calling apiV1OrganizationsOrganizationIDOauth2providersProviderIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/oauth2providers/{providerID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"providerID"}}`, encodeURIComponent(String(requestParameters.providerID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: Oauth2ProviderWriteToJSON(requestParameters.oauth2ProviderWrite),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an organization\'s identity provider.
     */
    async apiV1OrganizationsOrganizationIDOauth2providersProviderIDPut(requestParameters: ApiV1OrganizationsOrganizationIDOauth2providersProviderIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDOauth2providersProviderIDPutRaw(requestParameters, initOverrides);
    }

    /**
     * Updates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDelete.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDelete.');
        }

        if (requestParameters.allocationID === null || requestParameters.allocationID === undefined) {
            throw new runtime.RequiredError('allocationID','Required parameter requestParameters.allocationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/allocations/{allocationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))).replace(`{${"allocationID"}}`, encodeURIComponent(String(requestParameters.allocationID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Gets an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllocationRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGet.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGet.');
        }

        if (requestParameters.allocationID === null || requestParameters.allocationID === undefined) {
            throw new runtime.RequiredError('allocationID','Required parameter requestParameters.allocationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/allocations/{allocationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))).replace(`{${"allocationID"}}`, encodeURIComponent(String(requestParameters.allocationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllocationReadFromJSON(jsonValue));
    }

    /**
     * Gets an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGet(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllocationRead> {
        const response = await this.apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllocationRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPut.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPut.');
        }

        if (requestParameters.allocationID === null || requestParameters.allocationID === undefined) {
            throw new runtime.RequiredError('allocationID','Required parameter requestParameters.allocationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPut.');
        }

        if (requestParameters.allocationWrite === null || requestParameters.allocationWrite === undefined) {
            throw new runtime.RequiredError('allocationWrite','Required parameter requestParameters.allocationWrite was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/allocations/{allocationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))).replace(`{${"allocationID"}}`, encodeURIComponent(String(requestParameters.allocationID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AllocationWriteToJSON(requestParameters.allocationWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllocationReadFromJSON(jsonValue));
    }

    /**
     * Updates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPut(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllocationRead> {
        const response = await this.apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsAllocationIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllocationRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPost.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPost.');
        }

        if (requestParameters.allocationWrite === null || requestParameters.allocationWrite === undefined) {
            throw new runtime.RequiredError('allocationWrite','Required parameter requestParameters.allocationWrite was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/allocations`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AllocationWriteToJSON(requestParameters.allocationWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllocationReadFromJSON(jsonValue));
    }

    /**
     * Creates an allocation.
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPost(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllocationRead> {
        const response = await this.apiV1OrganizationsOrganizationIDProjectsProjectIDAllocationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Idempotent interface for removing external references from a resource. 
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDelete.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDelete.');
        }

        if (requestParameters.reference === null || requestParameters.reference === undefined) {
            throw new runtime.RequiredError('reference','Required parameter requestParameters.reference was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/references/{reference}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))).replace(`{${"reference"}}`, encodeURIComponent(String(requestParameters.reference))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Idempotent interface for removing external references from a resource. 
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDelete(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferenceDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Idempotent interface for adding external references to a resource. 
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePutRaw(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePut.');
        }

        if (requestParameters.projectID === null || requestParameters.projectID === undefined) {
            throw new runtime.RequiredError('projectID','Required parameter requestParameters.projectID was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePut.');
        }

        if (requestParameters.reference === null || requestParameters.reference === undefined) {
            throw new runtime.RequiredError('reference','Required parameter requestParameters.reference was null or undefined when calling apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/projects/{projectID}/references/{reference}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"projectID"}}`, encodeURIComponent(String(requestParameters.projectID))).replace(`{${"reference"}}`, encodeURIComponent(String(requestParameters.reference))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Idempotent interface for adding external references to a resource. 
     */
    async apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePut(requestParameters: ApiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDProjectsProjectIDReferencesReferencePutRaw(requestParameters, initOverrides);
    }

    /**
     * Sets quotas for the organization.
     */
    async apiV1OrganizationsOrganizationIDQuotasPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDQuotasPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuotasRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDQuotasPut.');
        }

        if (requestParameters.quotasWrite === null || requestParameters.quotasWrite === undefined) {
            throw new runtime.RequiredError('quotasWrite','Required parameter requestParameters.quotasWrite was null or undefined when calling apiV1OrganizationsOrganizationIDQuotasPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/quotas`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QuotasWriteToJSON(requestParameters.quotasWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuotasReadFromJSON(jsonValue));
    }

    /**
     * Sets quotas for the organization.
     */
    async apiV1OrganizationsOrganizationIDQuotasPut(requestParameters: ApiV1OrganizationsOrganizationIDQuotasPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuotasRead> {
        const response = await this.apiV1OrganizationsOrganizationIDQuotasPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows creation of a new organization.
     */
    async apiV1OrganizationsPostRaw(requestParameters: ApiV1OrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationRead>> {
        if (requestParameters.organizationWrite === null || requestParameters.organizationWrite === undefined) {
            throw new runtime.RequiredError('organizationWrite','Required parameter requestParameters.organizationWrite was null or undefined when calling apiV1OrganizationsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationWriteToJSON(requestParameters.organizationWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationReadFromJSON(jsonValue));
    }

    /**
     * Allows creation of a new organization.
     */
    async apiV1OrganizationsPost(requestParameters: ApiV1OrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationRead> {
        const response = await this.apiV1OrganizationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Complete the user signup process.
     */
    async apiV1SignupGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/signup`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Complete the user signup process.
     */
    async apiV1SignupGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1SignupGetRaw(initOverrides);
    }

    /**
     * Provides authentication and authorization as per the OAuth 2.0 specification. You may specify the \"openid\" scope in order to have an OpenID Connect identity token returned during code exchange.
     */
    async oauth2V2AuthorizationGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oauth2/v2/authorization`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Provides authentication and authorization as per the OAuth 2.0 specification. You may specify the \"openid\" scope in order to have an OpenID Connect identity token returned during code exchange.
     */
    async oauth2V2AuthorizationGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oauth2V2AuthorizationGetRaw(initOverrides);
    }

    /**
     * Provides authentication and authorization as per the OAuth 2.0 specification. You may specify the \"openid\" scope in order to have an OpenID Connect identity token returned during code exchange.
     */
    async oauth2V2AuthorizationPostRaw(requestParameters: Oauth2V2AuthorizationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authorizationRequestOptions === null || requestParameters.authorizationRequestOptions === undefined) {
            throw new runtime.RequiredError('authorizationRequestOptions','Required parameter requestParameters.authorizationRequestOptions was null or undefined when calling oauth2V2AuthorizationPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';

        const response = await this.request({
            path: `/oauth2/v2/authorization`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorizationRequestOptionsToJSON(requestParameters.authorizationRequestOptions),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Provides authentication and authorization as per the OAuth 2.0 specification. You may specify the \"openid\" scope in order to have an OpenID Connect identity token returned during code exchange.
     */
    async oauth2V2AuthorizationPost(requestParameters: Oauth2V2AuthorizationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oauth2V2AuthorizationPostRaw(requestParameters, initOverrides);
    }

    /**
     * Returns an array of public keys used to verify JWT ID tokens issued by this server.
     */
    async oauth2V2JwksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonWebKeySet>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oauth2/v2/jwks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonWebKeySetFromJSON(jsonValue));
    }

    /**
     * Returns an array of public keys used to verify JWT ID tokens issued by this server.
     */
    async oauth2V2JwksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonWebKeySet> {
        const response = await this.oauth2V2JwksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the user\'s email address, or chosen OAuth 2.0 provider back to the identity service to initiate the backend authentication and token exchange.
     */
    async oauth2V2LoginPostRaw(requestParameters: Oauth2V2LoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.loginRequestOptions === null || requestParameters.loginRequestOptions === undefined) {
            throw new runtime.RequiredError('loginRequestOptions','Required parameter requestParameters.loginRequestOptions was null or undefined when calling oauth2V2LoginPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';

        const response = await this.request({
            path: `/oauth2/v2/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestOptionsToJSON(requestParameters.loginRequestOptions),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the user\'s email address, or chosen OAuth 2.0 provider back to the identity service to initiate the backend authentication and token exchange.
     */
    async oauth2V2LoginPost(requestParameters: Oauth2V2LoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oauth2V2LoginPostRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the user\'s chosen organization name back to the identity service for creation of that organization, default user groups, and addition of that user to a group to allow login.
     */
    async oauth2V2OnboardPostRaw(requestParameters: Oauth2V2OnboardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.onboardRequestOptions === null || requestParameters.onboardRequestOptions === undefined) {
            throw new runtime.RequiredError('onboardRequestOptions','Required parameter requestParameters.onboardRequestOptions was null or undefined when calling oauth2V2OnboardPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';

        const response = await this.request({
            path: `/oauth2/v2/onboard`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OnboardRequestOptionsToJSON(requestParameters.onboardRequestOptions),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the user\'s chosen organization name back to the identity service for creation of that organization, default user groups, and addition of that user to a group to allow login.
     */
    async oauth2V2OnboardPost(requestParameters: Oauth2V2OnboardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oauth2V2OnboardPostRaw(requestParameters, initOverrides);
    }

    /**
     * Issues tokens according to the OAuth 2.0 specification. Supports the \"authorization_code\" grant for code-to-token exchange (optionally returning an OpenID Connect identity token), the \"refresh_token\" grant for transparent re-authentication, the \"client_credentials\" grant used by services in conjunction with X.509 client certificates, and the RFC 8693 token exchange grant (\"urn:ietf:params:oauth:grant-type:token-exchange\") used to exchange a validated source token for a signed JWT carrying delegated authorization claims.
     */
    async oauth2V2TokenPostRaw(requestParameters: Oauth2V2TokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters.tokenRequestOptions === null || requestParameters.tokenRequestOptions === undefined) {
            throw new runtime.RequiredError('tokenRequestOptions','Required parameter requestParameters.tokenRequestOptions was null or undefined when calling oauth2V2TokenPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';

        const response = await this.request({
            path: `/oauth2/v2/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRequestOptionsToJSON(requestParameters.tokenRequestOptions),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Issues tokens according to the OAuth 2.0 specification. Supports the \"authorization_code\" grant for code-to-token exchange (optionally returning an OpenID Connect identity token), the \"refresh_token\" grant for transparent re-authentication, the \"client_credentials\" grant used by services in conjunction with X.509 client certificates, and the RFC 8693 token exchange grant (\"urn:ietf:params:oauth:grant-type:token-exchange\") used to exchange a validated source token for a signed JWT carrying delegated authorization claims.
     */
    async oauth2V2TokenPost(requestParameters: Oauth2V2TokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.oauth2V2TokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns introspection information about an access token.
     */
    async oauth2V2UserinfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Userinfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oauth2/v2/userinfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserinfoFromJSON(jsonValue));
    }

    /**
     * Returns introspection information about an access token.
     */
    async oauth2V2UserinfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Userinfo> {
        const response = await this.oauth2V2UserinfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns introspection information about an access token.
     */
    async oauth2V2UserinfoPostRaw(requestParameters: Oauth2V2UserinfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Userinfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';

        const response = await this.request({
            path: `/oauth2/v2/userinfo`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserinfoRequestOptionsToJSON(requestParameters.userinfoRequestOptions),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserinfoFromJSON(jsonValue));
    }

    /**
     * Returns introspection information about an access token.
     */
    async oauth2V2UserinfoPost(requestParameters: Oauth2V2UserinfoPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Userinfo> {
        const response = await this.oauth2V2UserinfoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The Identity Service OAuth 2.0 implementation does not provide any direct authentication.  It instead delegates to a 3rd party identity provider. This endpoint allows a 3rd party authorization code to be returned to the Identity Service and exchanged for an identity token.
     */
    async oidcCallbackGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oidc/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The Identity Service OAuth 2.0 implementation does not provide any direct authentication.  It instead delegates to a 3rd party identity provider. This endpoint allows a 3rd party authorization code to be returned to the Identity Service and exchanged for an identity token.
     */
    async oidcCallbackGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oidcCallbackGetRaw(initOverrides);
    }

    /**
     * Reads the OIDC discovery page identifying all the required endpoints, and supported algorithms.
     */
    async wellKnownOpenidConfigurationGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenidConfiguration>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/.well-known/openid-configuration`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenidConfigurationFromJSON(jsonValue));
    }

    /**
     * Reads the OIDC discovery page identifying all the required endpoints, and supported algorithms.
     */
    async wellKnownOpenidConfigurationGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenidConfiguration> {
        const response = await this.wellKnownOpenidConfigurationGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Reads the OIDC discovery page identifying authorization severs.
     */
    async wellKnownOpenidProtectedResourceGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenidProtectedResource>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/.well-known/openid-protected-resource`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenidProtectedResourceFromJSON(jsonValue));
    }

    /**
     * Reads the OIDC discovery page identifying authorization severs.
     */
    async wellKnownOpenidProtectedResourceGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenidProtectedResource> {
        const response = await this.wellKnownOpenidProtectedResourceGetRaw(initOverrides);
        return await response.value();
    }

}
