/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GroupRead,
  GroupWrite,
  ModelError,
} from '../models/index';
import {
    GroupReadFromJSON,
    GroupReadToJSON,
    GroupWriteFromJSON,
    GroupWriteToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDGroupsGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDGroupsGroupidDeleteRequest {
    organizationID: string;
    groupid: string;
}

export interface ApiV1OrganizationsOrganizationIDGroupsGroupidGetRequest {
    organizationID: string;
    groupid: string;
}

export interface ApiV1OrganizationsOrganizationIDGroupsGroupidPutRequest {
    organizationID: string;
    groupid: string;
    groupWrite: GroupWrite;
}

export interface ApiV1OrganizationsOrganizationIDGroupsPostRequest {
    organizationID: string;
    groupWrite: GroupWrite;
}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     * Returns a list of groups that are defined for the organization.
     * List groups
     */
    async apiV1OrganizationsOrganizationIDGroupsGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupRead>>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/groups`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupReadFromJSON));
    }

    /**
     * Returns a list of groups that are defined for the organization.
     * List groups
     */
    async apiV1OrganizationsOrganizationIDGroupsGet(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupRead>> {
        const response = await this.apiV1OrganizationsOrganizationIDGroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows the deletion of an existing group.
     * Delete group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidDelete.');
        }

        if (requestParameters.groupid === null || requestParameters.groupid === undefined) {
            throw new runtime.RequiredError('groupid','Required parameter requestParameters.groupid was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/groups/{groupid}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"groupid"}}`, encodeURIComponent(String(requestParameters.groupid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows the deletion of an existing group.
     * Delete group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidDelete(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDGroupsGroupidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Allows a single group to be polled.
     * Get group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidGet.');
        }

        if (requestParameters.groupid === null || requestParameters.groupid === undefined) {
            throw new runtime.RequiredError('groupid','Required parameter requestParameters.groupid was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/groups/{groupid}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"groupid"}}`, encodeURIComponent(String(requestParameters.groupid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupReadFromJSON(jsonValue));
    }

    /**
     * Allows a single group to be polled.
     * Get group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidGet(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupRead> {
        const response = await this.apiV1OrganizationsOrganizationIDGroupsGroupidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows a group to be updated.
     * Update group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidPut.');
        }

        if (requestParameters.groupid === null || requestParameters.groupid === undefined) {
            throw new runtime.RequiredError('groupid','Required parameter requestParameters.groupid was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidPut.');
        }

        if (requestParameters.groupWrite === null || requestParameters.groupWrite === undefined) {
            throw new runtime.RequiredError('groupWrite','Required parameter requestParameters.groupWrite was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsGroupidPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/groups/{groupid}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"groupid"}}`, encodeURIComponent(String(requestParameters.groupid))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GroupWriteToJSON(requestParameters.groupWrite),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows a group to be updated.
     * Update group
     */
    async apiV1OrganizationsOrganizationIDGroupsGroupidPut(requestParameters: ApiV1OrganizationsOrganizationIDGroupsGroupidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDGroupsGroupidPutRaw(requestParameters, initOverrides);
    }

    /**
     * Allows creation of a new group.
     * Create group
     */
    async apiV1OrganizationsOrganizationIDGroupsPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDGroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsPost.');
        }

        if (requestParameters.groupWrite === null || requestParameters.groupWrite === undefined) {
            throw new runtime.RequiredError('groupWrite','Required parameter requestParameters.groupWrite was null or undefined when calling apiV1OrganizationsOrganizationIDGroupsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/groups`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupWriteToJSON(requestParameters.groupWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupReadFromJSON(jsonValue));
    }

    /**
     * Allows creation of a new group.
     * Create group
     */
    async apiV1OrganizationsOrganizationIDGroupsPost(requestParameters: ApiV1OrganizationsOrganizationIDGroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupRead> {
        const response = await this.apiV1OrganizationsOrganizationIDGroupsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
