/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  OrganizationRead,
  OrganizationWrite,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    OrganizationReadFromJSON,
    OrganizationReadToJSON,
    OrganizationWriteFromJSON,
    OrganizationWriteToJSON,
} from '../models/index';

export interface ApiV1OrganizationsGetRequest {
    email?: string;
}

export interface ApiV1OrganizationsOrganizationIDGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDPutRequest {
    organizationID: string;
    organizationWrite: OrganizationWrite;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Returns a list of organizations that the user is a member of.  If an email address is provided in the query this allows a user with sufficient privilege to check if a given user is a member of any organizations.
     * List organizations
     */
    async apiV1OrganizationsGetRaw(requestParameters: ApiV1OrganizationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationRead>>> {
        const queryParameters: any = {};

        if (requestParameters.email !== undefined) {
            queryParameters['email'] = requestParameters.email;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationReadFromJSON));
    }

    /**
     * Returns a list of organizations that the user is a member of.  If an email address is provided in the query this allows a user with sufficient privilege to check if a given user is a member of any organizations.
     * List organizations
     */
    async apiV1OrganizationsGet(requestParameters: ApiV1OrganizationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationRead>> {
        const response = await this.apiV1OrganizationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an organization.
     * Get organization
     */
    async apiV1OrganizationsOrganizationIDGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationReadFromJSON(jsonValue));
    }

    /**
     * Get an organization.
     * Get organization
     */
    async apiV1OrganizationsOrganizationIDGet(requestParameters: ApiV1OrganizationsOrganizationIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationRead> {
        const response = await this.apiV1OrganizationsOrganizationIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an organization.
     * Update organization
     */
    async apiV1OrganizationsOrganizationIDPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDPut.');
        }

        if (requestParameters.organizationWrite === null || requestParameters.organizationWrite === undefined) {
            throw new runtime.RequiredError('organizationWrite','Required parameter requestParameters.organizationWrite was null or undefined when calling apiV1OrganizationsOrganizationIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationWriteToJSON(requestParameters.organizationWrite),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an organization.
     * Update organization
     */
    async apiV1OrganizationsOrganizationIDPut(requestParameters: ApiV1OrganizationsOrganizationIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDPutRaw(requestParameters, initOverrides);
    }

}
