/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  QuotasRead,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    QuotasReadFromJSON,
    QuotasReadToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDQuotasGetRequest {
    organizationID: string;
}

/**
 * 
 */
export class QuotasApi extends runtime.BaseAPI {

    /**
     * Gets quotas for the organization.
     * List quotas
     */
    async apiV1OrganizationsOrganizationIDQuotasGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDQuotasGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuotasRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDQuotasGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/quotas`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuotasReadFromJSON(jsonValue));
    }

    /**
     * Gets quotas for the organization.
     * List quotas
     */
    async apiV1OrganizationsOrganizationIDQuotasGet(requestParameters: ApiV1OrganizationsOrganizationIDQuotasGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuotasRead> {
        const response = await this.apiV1OrganizationsOrganizationIDQuotasGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
