/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  ServiceAccountCreate,
  ServiceAccountRead,
  ServiceAccountWrite,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    ServiceAccountCreateFromJSON,
    ServiceAccountCreateToJSON,
    ServiceAccountReadFromJSON,
    ServiceAccountReadToJSON,
    ServiceAccountWriteFromJSON,
    ServiceAccountWriteToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDServiceaccountsGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDServiceaccountsPostRequest {
    organizationID: string;
    serviceAccountWrite: ServiceAccountWrite;
}

export interface ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDeleteRequest {
    organizationID: string;
    serviceAccountID: string;
}

export interface ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPutRequest {
    organizationID: string;
    serviceAccountID: string;
    serviceAccountWrite: ServiceAccountWrite;
}

export interface ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePostRequest {
    organizationID: string;
    serviceAccountID: string;
}

/**
 * 
 */
export class ServiceAccountsApi extends runtime.BaseAPI {

    /**
     * Lists all service accounts.
     * List service accounts
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceAccountRead>>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/serviceaccounts`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceAccountReadFromJSON));
    }

    /**
     * Lists all service accounts.
     * List service accounts
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsGet(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceAccountRead>> {
        const response = await this.apiV1OrganizationsOrganizationIDServiceaccountsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new service account and returns an access token,  The returned access token can only be read once.
     * Create service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceAccountCreate>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsPost.');
        }

        if (requestParameters.serviceAccountWrite === null || requestParameters.serviceAccountWrite === undefined) {
            throw new runtime.RequiredError('serviceAccountWrite','Required parameter requestParameters.serviceAccountWrite was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/serviceaccounts`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceAccountWriteToJSON(requestParameters.serviceAccountWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceAccountCreateFromJSON(jsonValue));
    }

    /**
     * Creates a new service account and returns an access token,  The returned access token can only be read once.
     * Create service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsPost(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceAccountCreate> {
        const response = await this.apiV1OrganizationsOrganizationIDServiceaccountsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a service account and revokes an access token.
     * Delete service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDelete.');
        }

        if (requestParameters.serviceAccountID === null || requestParameters.serviceAccountID === undefined) {
            throw new runtime.RequiredError('serviceAccountID','Required parameter requestParameters.serviceAccountID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/serviceaccounts/{serviceAccountID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"serviceAccountID"}}`, encodeURIComponent(String(requestParameters.serviceAccountID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a service account and revokes an access token.
     * Delete service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Updates a service account.
     * Update service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceAccountRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPut.');
        }

        if (requestParameters.serviceAccountID === null || requestParameters.serviceAccountID === undefined) {
            throw new runtime.RequiredError('serviceAccountID','Required parameter requestParameters.serviceAccountID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPut.');
        }

        if (requestParameters.serviceAccountWrite === null || requestParameters.serviceAccountWrite === undefined) {
            throw new runtime.RequiredError('serviceAccountWrite','Required parameter requestParameters.serviceAccountWrite was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/serviceaccounts/{serviceAccountID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"serviceAccountID"}}`, encodeURIComponent(String(requestParameters.serviceAccountID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceAccountWriteToJSON(requestParameters.serviceAccountWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceAccountReadFromJSON(jsonValue));
    }

    /**
     * Updates a service account.
     * Update service account
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPut(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceAccountRead> {
        const response = await this.apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotates a service account\'s access token. The returned access token can only be read once.
     * Rotate service account token
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePostRaw(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceAccountCreate>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePost.');
        }

        if (requestParameters.serviceAccountID === null || requestParameters.serviceAccountID === undefined) {
            throw new runtime.RequiredError('serviceAccountID','Required parameter requestParameters.serviceAccountID was null or undefined when calling apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/serviceaccounts/{serviceAccountID}/rotate`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"serviceAccountID"}}`, encodeURIComponent(String(requestParameters.serviceAccountID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceAccountCreateFromJSON(jsonValue));
    }

    /**
     * Rotates a service account\'s access token. The returned access token can only be read once.
     * Rotate service account token
     */
    async apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePost(requestParameters: ApiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceAccountCreate> {
        const response = await this.apiV1OrganizationsOrganizationIDServiceaccountsServiceAccountIDRotatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
