/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  UserRead,
  UserWrite,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    UserReadFromJSON,
    UserReadToJSON,
    UserWriteFromJSON,
    UserWriteToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDUsersGetRequest {
    organizationID: string;
}

export interface ApiV1OrganizationsOrganizationIDUsersPostRequest {
    organizationID: string;
    userWrite: UserWrite;
}

export interface ApiV1OrganizationsOrganizationIDUsersUserIDDeleteRequest {
    organizationID: string;
    userID: string;
}

export interface ApiV1OrganizationsOrganizationIDUsersUserIDPutRequest {
    organizationID: string;
    userID: string;
    userWrite: UserWrite;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Lists all users.
     * List users
     */
    async apiV1OrganizationsOrganizationIDUsersGetRaw(requestParameters: ApiV1OrganizationsOrganizationIDUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRead>>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/users`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserReadFromJSON));
    }

    /**
     * Lists all users.
     * List users
     */
    async apiV1OrganizationsOrganizationIDUsersGet(requestParameters: ApiV1OrganizationsOrganizationIDUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRead>> {
        const response = await this.apiV1OrganizationsOrganizationIDUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new user and associates with a set of groups.
     * Create user
     */
    async apiV1OrganizationsOrganizationIDUsersPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersPost.');
        }

        if (requestParameters.userWrite === null || requestParameters.userWrite === undefined) {
            throw new runtime.RequiredError('userWrite','Required parameter requestParameters.userWrite was null or undefined when calling apiV1OrganizationsOrganizationIDUsersPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/users`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserWriteToJSON(requestParameters.userWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Creates a new user and associates with a set of groups.
     * Create user
     */
    async apiV1OrganizationsOrganizationIDUsersPost(requestParameters: ApiV1OrganizationsOrganizationIDUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.apiV1OrganizationsOrganizationIDUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a user and disassociates them with all groups they are a member of.
     * Delete user
     */
    async apiV1OrganizationsOrganizationIDUsersUserIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDUsersUserIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersUserIDDelete.');
        }

        if (requestParameters.userID === null || requestParameters.userID === undefined) {
            throw new runtime.RequiredError('userID','Required parameter requestParameters.userID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersUserIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/users/{userID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters.userID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a user and disassociates them with all groups they are a member of.
     * Delete user
     */
    async apiV1OrganizationsOrganizationIDUsersUserIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDUsersUserIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDUsersUserIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Updates a user.
     * Update user
     */
    async apiV1OrganizationsOrganizationIDUsersUserIDPutRaw(requestParameters: ApiV1OrganizationsOrganizationIDUsersUserIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersUserIDPut.');
        }

        if (requestParameters.userID === null || requestParameters.userID === undefined) {
            throw new runtime.RequiredError('userID','Required parameter requestParameters.userID was null or undefined when calling apiV1OrganizationsOrganizationIDUsersUserIDPut.');
        }

        if (requestParameters.userWrite === null || requestParameters.userWrite === undefined) {
            throw new runtime.RequiredError('userWrite','Required parameter requestParameters.userWrite was null or undefined when calling apiV1OrganizationsOrganizationIDUsersUserIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/users/{userID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters.userID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserWriteToJSON(requestParameters.userWrite),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Updates a user.
     * Update user
     */
    async apiV1OrganizationsOrganizationIDUsersUserIDPut(requestParameters: ApiV1OrganizationsOrganizationIDUsersUserIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.apiV1OrganizationsOrganizationIDUsersUserIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
