/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * CPU architecture.
 * @export
 */
export const Architecture = {
    X8664: 'x86_64',
    Aarch64: 'aarch64'
} as const;
export type Architecture = typeof Architecture[keyof typeof Architecture];


export function ArchitectureFromJSON(json: any): Architecture {
    return ArchitectureFromJSONTyped(json, false);
}

export function ArchitectureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Architecture {
    return json as Architecture;
}

export function ArchitectureToJSON(value?: Architecture | null): any {
    return value as any;
}

