/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Bearer token transport method
 * @export
 */
export const BearerMethod = {
    Header: 'header',
    Body: 'body',
    Query: 'query'
} as const;
export type BearerMethod = typeof BearerMethod[keyof typeof BearerMethod];


export function BearerMethodFromJSON(json: any): BearerMethod {
    return BearerMethodFromJSONTyped(json, false);
}

export function BearerMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearerMethod {
    return json as BearerMethod;
}

export function BearerMethodToJSON(value?: BearerMethod | null): any {
    return value as any;
}

