/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Defines explicit control plane topology. When not specified, the platform
 * will automatically select an appropriate flavor.
 * @export
 * @interface KubernetesClusterControlPlane
 */
export interface KubernetesClusterControlPlane {
    /**
     * Flavor ID for control plane nodes.
     * @type {string}
     * @memberof KubernetesClusterControlPlane
     */
    flavorId: string;
    /**
     * Number of control plane replicas. Must be an odd number to
     * maintain quorum. Defaults to 3 if not specified.
     * @type {number}
     * @memberof KubernetesClusterControlPlane
     */
    replicas?: number;
}

/**
 * Check if a given object implements the KubernetesClusterControlPlane interface.
 */
export function instanceOfKubernetesClusterControlPlane(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "flavorId" in value;

    return isInstance;
}

export function KubernetesClusterControlPlaneFromJSON(json: any): KubernetesClusterControlPlane {
    return KubernetesClusterControlPlaneFromJSONTyped(json, false);
}

export function KubernetesClusterControlPlaneFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubernetesClusterControlPlane {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flavorId': json['flavorId'],
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
    };
}

export function KubernetesClusterControlPlaneToJSON(value?: KubernetesClusterControlPlane | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flavorId': value.flavorId,
        'replicas': value.replicas,
    };
}

