/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Cluster feature flags.
 * @export
 * @interface KubernetesClusterFeatures
 */
export interface KubernetesClusterFeatures {
    /**
     * Enables and hardware operators and drivers for the cluster e.g.
     * GPU operator, network configuration, etc.
     * @type {boolean}
     * @memberof KubernetesClusterFeatures
     */
    hardwareEnablement: boolean;
}

/**
 * Check if a given object implements the KubernetesClusterFeatures interface.
 */
export function instanceOfKubernetesClusterFeatures(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hardwareEnablement" in value;

    return isInstance;
}

export function KubernetesClusterFeaturesFromJSON(json: any): KubernetesClusterFeatures {
    return KubernetesClusterFeaturesFromJSONTyped(json, false);
}

export function KubernetesClusterFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubernetesClusterFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hardwareEnablement': json['hardwareEnablement'],
    };
}

export function KubernetesClusterFeaturesToJSON(value?: KubernetesClusterFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hardwareEnablement': value.hardwareEnablement,
    };
}

