/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Kubernetes cluster features configuration.
 * @export
 * @interface KubernetesClusterFeatures
 */
export interface KubernetesClusterFeatures {
    /**
     * Enables the provision of the observability agent add-on.
     * This deploys telemetry collectors for forwarding cluster observability data.
     * @type {boolean}
     * @memberof KubernetesClusterFeatures
     */
    observabilityAgent?: boolean;
}

/**
 * Check if a given object implements the KubernetesClusterFeatures interface.
 */
export function instanceOfKubernetesClusterFeatures(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KubernetesClusterFeaturesFromJSON(json: any): KubernetesClusterFeatures {
    return KubernetesClusterFeaturesFromJSONTyped(json, false);
}

export function KubernetesClusterFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubernetesClusterFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'observabilityAgent': !exists(json, 'observabilityAgent') ? undefined : json['observabilityAgent'],
    };
}

export function KubernetesClusterFeaturesToJSON(value?: KubernetesClusterFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'observabilityAgent': value.observabilityAgent,
    };
}

