/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BearerMethod } from './BearerMethod';
import {
    BearerMethodFromJSON,
    BearerMethodFromJSONTyped,
    BearerMethodToJSON,
} from './BearerMethod';

/**
 * OpenID athentication server discovery configuration.
 * @export
 * @interface OpenidProtectedResource
 */
export interface OpenidProtectedResource {
    /**
     * The protected resource's scheme and hostname.
     * @type {string}
     * @memberof OpenidProtectedResource
     */
    resource: string;
    /**
     * List of authorization servers that can grant access to the resource.
     * @type {Array<string>}
     * @memberof OpenidProtectedResource
     */
    authorizationServers: Array<string>;
    /**
     * A set of OIDC scopes that are required for authorization.
     * @type {Array<string>}
     * @memberof OpenidProtectedResource
     */
    scopesSupported: Array<string>;
    /**
     * A set of bearer token transport methods supported by the protected endpoint.
     * @type {Array<BearerMethod>}
     * @memberof OpenidProtectedResource
     */
    bearerMethodsSupported: Array<BearerMethod>;
}

/**
 * Check if a given object implements the OpenidProtectedResource interface.
 */
export function instanceOfOpenidProtectedResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resource" in value;
    isInstance = isInstance && "authorizationServers" in value;
    isInstance = isInstance && "scopesSupported" in value;
    isInstance = isInstance && "bearerMethodsSupported" in value;

    return isInstance;
}

export function OpenidProtectedResourceFromJSON(json: any): OpenidProtectedResource {
    return OpenidProtectedResourceFromJSONTyped(json, false);
}

export function OpenidProtectedResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenidProtectedResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resource': json['resource'],
        'authorizationServers': json['authorization_servers'],
        'scopesSupported': json['scopes_supported'],
        'bearerMethodsSupported': ((json['bearer_methods_supported'] as Array<any>).map(BearerMethodFromJSON)),
    };
}

export function OpenidProtectedResourceToJSON(value?: OpenidProtectedResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource': value.resource,
        'authorization_servers': value.authorizationServers,
        'scopes_supported': value.scopesSupported,
        'bearer_methods_supported': ((value.bearerMethodsSupported as Array<any>).map(BearerMethodToJSON)),
    };
}

