/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  StorageV2Create,
  StorageV2Read,
  StorageV2Update,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    StorageV2CreateFromJSON,
    StorageV2CreateToJSON,
    StorageV2ReadFromJSON,
    StorageV2ReadToJSON,
    StorageV2UpdateFromJSON,
    StorageV2UpdateToJSON,
} from '../models/index';

export interface ApiV2FilestorageFilestorageIDDeleteRequest {
    filestorageID: string;
}

export interface ApiV2FilestorageFilestorageIDGetRequest {
    filestorageID: string;
}

export interface ApiV2FilestorageFilestorageIDPutRequest {
    filestorageID: string;
    storageV2Update?: StorageV2Update;
}

export interface ApiV2FilestorageGetRequest {
    tag?: Array<string>;
    organizationID?: Array<string>;
    projectID?: Array<string>;
    regionID?: Array<string>;
}

export interface ApiV2FilestoragePostRequest {
    storageV2Create?: StorageV2Create;
}

/**
 * 
 */
export class FileStorageApi extends runtime.BaseAPI {

    /**
     * Delete a storage.
     * Delete file storage
     */
    async apiV2FilestorageFilestorageIDDeleteRaw(requestParameters: ApiV2FilestorageFilestorageIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.filestorageID === null || requestParameters.filestorageID === undefined) {
            throw new runtime.RequiredError('filestorageID','Required parameter requestParameters.filestorageID was null or undefined when calling apiV2FilestorageFilestorageIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorage/{filestorageID}`.replace(`{${"filestorageID"}}`, encodeURIComponent(String(requestParameters.filestorageID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a storage.
     * Delete file storage
     */
    async apiV2FilestorageFilestorageIDDelete(requestParameters: ApiV2FilestorageFilestorageIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2FilestorageFilestorageIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get all storage information this ID.
     * Get file storage
     */
    async apiV2FilestorageFilestorageIDGetRaw(requestParameters: ApiV2FilestorageFilestorageIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageV2Read>> {
        if (requestParameters.filestorageID === null || requestParameters.filestorageID === undefined) {
            throw new runtime.RequiredError('filestorageID','Required parameter requestParameters.filestorageID was null or undefined when calling apiV2FilestorageFilestorageIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorage/{filestorageID}`.replace(`{${"filestorageID"}}`, encodeURIComponent(String(requestParameters.filestorageID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageV2ReadFromJSON(jsonValue));
    }

    /**
     * Get all storage information this ID.
     * Get file storage
     */
    async apiV2FilestorageFilestorageIDGet(requestParameters: ApiV2FilestorageFilestorageIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageV2Read> {
        const response = await this.apiV2FilestorageFilestorageIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update this storage.
     * Update file storage
     */
    async apiV2FilestorageFilestorageIDPutRaw(requestParameters: ApiV2FilestorageFilestorageIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageV2Read>> {
        if (requestParameters.filestorageID === null || requestParameters.filestorageID === undefined) {
            throw new runtime.RequiredError('filestorageID','Required parameter requestParameters.filestorageID was null or undefined when calling apiV2FilestorageFilestorageIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorage/{filestorageID}`.replace(`{${"filestorageID"}}`, encodeURIComponent(String(requestParameters.filestorageID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StorageV2UpdateToJSON(requestParameters.storageV2Update),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageV2ReadFromJSON(jsonValue));
    }

    /**
     * Update this storage.
     * Update file storage
     */
    async apiV2FilestorageFilestorageIDPut(requestParameters: ApiV2FilestorageFilestorageIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageV2Read> {
        const response = await this.apiV2FilestorageFilestorageIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List storage for project.
     * List file storage
     */
    async apiV2FilestorageGetRaw(requestParameters: ApiV2FilestorageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StorageV2Read>>> {
        const queryParameters: any = {};

        if (requestParameters.tag) {
            queryParameters['tag'] = requestParameters.tag.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.organizationID) {
            queryParameters['organizationID'] = requestParameters.organizationID;
        }

        if (requestParameters.projectID) {
            queryParameters['projectID'] = requestParameters.projectID;
        }

        if (requestParameters.regionID) {
            queryParameters['regionID'] = requestParameters.regionID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StorageV2ReadFromJSON));
    }

    /**
     * List storage for project.
     * List file storage
     */
    async apiV2FilestorageGet(requestParameters: ApiV2FilestorageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StorageV2Read>> {
        const response = await this.apiV2FilestorageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new storage.
     * Create file storage
     */
    async apiV2FilestoragePostRaw(requestParameters: ApiV2FilestoragePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageV2Read>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorage`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageV2CreateToJSON(requestParameters.storageV2Create),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageV2ReadFromJSON(jsonValue));
    }

    /**
     * Create a new storage.
     * Create file storage
     */
    async apiV2FilestoragePost(requestParameters: ApiV2FilestoragePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageV2Read> {
        const response = await this.apiV2FilestoragePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
