/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  StorageClassV2Read,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    StorageClassV2ReadFromJSON,
    StorageClassV2ReadToJSON,
} from '../models/index';

export interface ApiV2FilestorageclassesGetRequest {
    regionID?: Array<string>;
}

/**
 * 
 */
export class FileStorageClassesApi extends runtime.BaseAPI {

    /**
     * List storage classes.
     * List file storage classes
     */
    async apiV2FilestorageclassesGetRaw(requestParameters: ApiV2FilestorageclassesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StorageClassV2Read>>> {
        const queryParameters: any = {};

        if (requestParameters.regionID) {
            queryParameters['regionID'] = requestParameters.regionID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/filestorageclasses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StorageClassV2ReadFromJSON));
    }

    /**
     * List storage classes.
     * List file storage classes
     */
    async apiV2FilestorageclassesGet(requestParameters: ApiV2FilestorageclassesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StorageClassV2Read>> {
        const response = await this.apiV2FilestorageclassesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
