/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Image,
  ImageCreate,
  ImageState,
  ModelError,
} from '../models/index';
import {
    ImageFromJSON,
    ImageToJSON,
    ImageCreateFromJSON,
    ImageCreateToJSON,
    ImageStateFromJSON,
    ImageStateToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/index';

export interface ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDeleteRequest {
    organizationID: string;
    regionID: string;
    imageID: string;
}

export interface ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesPostRequest {
    organizationID: string;
    regionID: string;
    imageCreate?: ImageCreate;
}

export interface ApiV2RegionsRegionIDImagesGetRequest {
    regionID: string;
    organizationID?: Array<string>;
    scope?: ApiV2RegionsRegionIDImagesGetScopeEnum;
    status?: Array<ImageState>;
}

/**
 * 
 */
export class ImagesApi extends runtime.BaseAPI {

    /**
     * Delete a compute image.
     */
    async apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDeleteRaw(requestParameters: ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDelete.');
        }

        if (requestParameters.regionID === null || requestParameters.regionID === undefined) {
            throw new runtime.RequiredError('regionID','Required parameter requestParameters.regionID was null or undefined when calling apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDelete.');
        }

        if (requestParameters.imageID === null || requestParameters.imageID === undefined) {
            throw new runtime.RequiredError('imageID','Required parameter requestParameters.imageID was null or undefined when calling apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/regions/{regionID}/images/{imageID}`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"regionID"}}`, encodeURIComponent(String(requestParameters.regionID))).replace(`{${"imageID"}}`, encodeURIComponent(String(requestParameters.imageID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a compute image.
     */
    async apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDelete(requestParameters: ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1OrganizationsOrganizationIDRegionsRegionIDImagesImageIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Create a compute image from a public URL.  Only raw images are supported, other container formats such as qcow2 must be first converted to a raw image.
     * Create a compute image from a disk image URL.
     */
    async apiV1OrganizationsOrganizationIDRegionsRegionIDImagesPostRaw(requestParameters: ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        if (requestParameters.organizationID === null || requestParameters.organizationID === undefined) {
            throw new runtime.RequiredError('organizationID','Required parameter requestParameters.organizationID was null or undefined when calling apiV1OrganizationsOrganizationIDRegionsRegionIDImagesPost.');
        }

        if (requestParameters.regionID === null || requestParameters.regionID === undefined) {
            throw new runtime.RequiredError('regionID','Required parameter requestParameters.regionID was null or undefined when calling apiV1OrganizationsOrganizationIDRegionsRegionIDImagesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/organizations/{organizationID}/regions/{regionID}/images`.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters.organizationID))).replace(`{${"regionID"}}`, encodeURIComponent(String(requestParameters.regionID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageCreateToJSON(requestParameters.imageCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Create a compute image from a public URL.  Only raw images are supported, other container formats such as qcow2 must be first converted to a raw image.
     * Create a compute image from a disk image URL.
     */
    async apiV1OrganizationsOrganizationIDRegionsRegionIDImagesPost(requestParameters: ApiV1OrganizationsOrganizationIDRegionsRegionIDImagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.apiV1OrganizationsOrganizationIDRegionsRegionIDImagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List compute disk images
     */
    async apiV2RegionsRegionIDImagesGetRaw(requestParameters: ApiV2RegionsRegionIDImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Image>>> {
        if (requestParameters.regionID === null || requestParameters.regionID === undefined) {
            throw new runtime.RequiredError('regionID','Required parameter requestParameters.regionID was null or undefined when calling apiV2RegionsRegionIDImagesGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.organizationID) {
            queryParameters['organizationID'] = requestParameters.organizationID;
        }

        if (requestParameters.scope !== undefined) {
            queryParameters['scope'] = requestParameters.scope;
        }

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/regions/{regionID}/images`.replace(`{${"regionID"}}`, encodeURIComponent(String(requestParameters.regionID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageFromJSON));
    }

    /**
     * List compute disk images
     */
    async apiV2RegionsRegionIDImagesGet(requestParameters: ApiV2RegionsRegionIDImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Image>> {
        const response = await this.apiV2RegionsRegionIDImagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiV2RegionsRegionIDImagesGetScopeEnum = {
    Owned: 'owned',
    Available: 'available'
} as const;
export type ApiV2RegionsRegionIDImagesGetScopeEnum = typeof ApiV2RegionsRegionIDImagesGetScopeEnum[keyof typeof ApiV2RegionsRegionIDImagesGetScopeEnum];
