/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  SecurityGroupV2Create,
  SecurityGroupV2Read,
  SecurityGroupV2Update,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    SecurityGroupV2CreateFromJSON,
    SecurityGroupV2CreateToJSON,
    SecurityGroupV2ReadFromJSON,
    SecurityGroupV2ReadToJSON,
    SecurityGroupV2UpdateFromJSON,
    SecurityGroupV2UpdateToJSON,
} from '../models/index';

export interface ApiV2SecuritygroupsGetRequest {
    tag?: Array<string>;
    organizationID?: Array<string>;
    projectID?: Array<string>;
    regionID?: Array<string>;
    networkID?: Array<string>;
}

export interface ApiV2SecuritygroupsPostRequest {
    securityGroupV2Create?: SecurityGroupV2Create;
}

export interface ApiV2SecuritygroupsSecurityGroupIDDeleteRequest {
    securityGroupID: string;
}

export interface ApiV2SecuritygroupsSecurityGroupIDGetRequest {
    securityGroupID: string;
}

export interface ApiV2SecuritygroupsSecurityGroupIDPutRequest {
    securityGroupID: string;
    securityGroupV2Update?: SecurityGroupV2Update;
}

/**
 * 
 */
export class SecurityGroupsApi extends runtime.BaseAPI {

    /**
     * List security groups.
     * List security groups
     */
    async apiV2SecuritygroupsGetRaw(requestParameters: ApiV2SecuritygroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SecurityGroupV2Read>>> {
        const queryParameters: any = {};

        if (requestParameters.tag) {
            queryParameters['tag'] = requestParameters.tag.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.organizationID) {
            queryParameters['organizationID'] = requestParameters.organizationID;
        }

        if (requestParameters.projectID) {
            queryParameters['projectID'] = requestParameters.projectID;
        }

        if (requestParameters.regionID) {
            queryParameters['regionID'] = requestParameters.regionID;
        }

        if (requestParameters.networkID) {
            queryParameters['networkID'] = requestParameters.networkID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/securitygroups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SecurityGroupV2ReadFromJSON));
    }

    /**
     * List security groups.
     * List security groups
     */
    async apiV2SecuritygroupsGet(requestParameters: ApiV2SecuritygroupsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SecurityGroupV2Read>> {
        const response = await this.apiV2SecuritygroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new security group.
     * Create security group
     */
    async apiV2SecuritygroupsPostRaw(requestParameters: ApiV2SecuritygroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityGroupV2Read>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/securitygroups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SecurityGroupV2CreateToJSON(requestParameters.securityGroupV2Create),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityGroupV2ReadFromJSON(jsonValue));
    }

    /**
     * Create a new security group.
     * Create security group
     */
    async apiV2SecuritygroupsPost(requestParameters: ApiV2SecuritygroupsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityGroupV2Read> {
        const response = await this.apiV2SecuritygroupsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a security groups.
     * Delete security group
     */
    async apiV2SecuritygroupsSecurityGroupIDDeleteRaw(requestParameters: ApiV2SecuritygroupsSecurityGroupIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.securityGroupID === null || requestParameters.securityGroupID === undefined) {
            throw new runtime.RequiredError('securityGroupID','Required parameter requestParameters.securityGroupID was null or undefined when calling apiV2SecuritygroupsSecurityGroupIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/securitygroups/{securityGroupID}`.replace(`{${"securityGroupID"}}`, encodeURIComponent(String(requestParameters.securityGroupID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a security groups.
     * Delete security group
     */
    async apiV2SecuritygroupsSecurityGroupIDDelete(requestParameters: ApiV2SecuritygroupsSecurityGroupIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2SecuritygroupsSecurityGroupIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get a security group.
     * Get security group
     */
    async apiV2SecuritygroupsSecurityGroupIDGetRaw(requestParameters: ApiV2SecuritygroupsSecurityGroupIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityGroupV2Read>> {
        if (requestParameters.securityGroupID === null || requestParameters.securityGroupID === undefined) {
            throw new runtime.RequiredError('securityGroupID','Required parameter requestParameters.securityGroupID was null or undefined when calling apiV2SecuritygroupsSecurityGroupIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/securitygroups/{securityGroupID}`.replace(`{${"securityGroupID"}}`, encodeURIComponent(String(requestParameters.securityGroupID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityGroupV2ReadFromJSON(jsonValue));
    }

    /**
     * Get a security group.
     * Get security group
     */
    async apiV2SecuritygroupsSecurityGroupIDGet(requestParameters: ApiV2SecuritygroupsSecurityGroupIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityGroupV2Read> {
        const response = await this.apiV2SecuritygroupsSecurityGroupIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a security group.
     * Update security group
     */
    async apiV2SecuritygroupsSecurityGroupIDPutRaw(requestParameters: ApiV2SecuritygroupsSecurityGroupIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityGroupV2Read>> {
        if (requestParameters.securityGroupID === null || requestParameters.securityGroupID === undefined) {
            throw new runtime.RequiredError('securityGroupID','Required parameter requestParameters.securityGroupID was null or undefined when calling apiV2SecuritygroupsSecurityGroupIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/securitygroups/{securityGroupID}`.replace(`{${"securityGroupID"}}`, encodeURIComponent(String(requestParameters.securityGroupID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SecurityGroupV2UpdateToJSON(requestParameters.securityGroupV2Update),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityGroupV2ReadFromJSON(jsonValue));
    }

    /**
     * Update a security group.
     * Update security group
     */
    async apiV2SecuritygroupsSecurityGroupIDPut(requestParameters: ApiV2SecuritygroupsSecurityGroupIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityGroupV2Read> {
        const response = await this.apiV2SecuritygroupsSecurityGroupIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
