/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelError,
  SshCertificateAuthorityV2Create,
  SshCertificateAuthorityV2Read,
} from '../models/index';
import {
    ModelErrorFromJSON,
    ModelErrorToJSON,
    SshCertificateAuthorityV2CreateFromJSON,
    SshCertificateAuthorityV2CreateToJSON,
    SshCertificateAuthorityV2ReadFromJSON,
    SshCertificateAuthorityV2ReadToJSON,
} from '../models/index';

export interface ApiV2SshcertificateauthoritiesGetRequest {
    tag?: Array<string>;
    organizationID?: Array<string>;
    projectID?: Array<string>;
}

export interface ApiV2SshcertificateauthoritiesPostRequest {
    sshCertificateAuthorityV2Create?: SshCertificateAuthorityV2Create;
}

export interface ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDDeleteRequest {
    sshCertificateAuthorityID: string;
}

export interface ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDGetRequest {
    sshCertificateAuthorityID: string;
}

/**
 * 
 */
export class SSHCertificateAuthoritiesApi extends runtime.BaseAPI {

    /**
     * List SSH certificate authorities.
     * List SSH certificate authorities
     */
    async apiV2SshcertificateauthoritiesGetRaw(requestParameters: ApiV2SshcertificateauthoritiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SshCertificateAuthorityV2Read>>> {
        const queryParameters: any = {};

        if (requestParameters.tag) {
            queryParameters['tag'] = requestParameters.tag.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.organizationID) {
            queryParameters['organizationID'] = requestParameters.organizationID;
        }

        if (requestParameters.projectID) {
            queryParameters['projectID'] = requestParameters.projectID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/sshcertificateauthorities`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SshCertificateAuthorityV2ReadFromJSON));
    }

    /**
     * List SSH certificate authorities.
     * List SSH certificate authorities
     */
    async apiV2SshcertificateauthoritiesGet(requestParameters: ApiV2SshcertificateauthoritiesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SshCertificateAuthorityV2Read>> {
        const response = await this.apiV2SshcertificateauthoritiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new SSH certificate authority.
     * Create SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesPostRaw(requestParameters: ApiV2SshcertificateauthoritiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SshCertificateAuthorityV2Read>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/sshcertificateauthorities`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SshCertificateAuthorityV2CreateToJSON(requestParameters.sshCertificateAuthorityV2Create),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SshCertificateAuthorityV2ReadFromJSON(jsonValue));
    }

    /**
     * Create a new SSH certificate authority.
     * Create SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesPost(requestParameters: ApiV2SshcertificateauthoritiesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SshCertificateAuthorityV2Read> {
        const response = await this.apiV2SshcertificateauthoritiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an SSH certificate authority.
     * Delete SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesSshCertificateAuthorityIDDeleteRaw(requestParameters: ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.sshCertificateAuthorityID === null || requestParameters.sshCertificateAuthorityID === undefined) {
            throw new runtime.RequiredError('sshCertificateAuthorityID','Required parameter requestParameters.sshCertificateAuthorityID was null or undefined when calling apiV2SshcertificateauthoritiesSshCertificateAuthorityIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/sshcertificateauthorities/{sshCertificateAuthorityID}`.replace(`{${"sshCertificateAuthorityID"}}`, encodeURIComponent(String(requestParameters.sshCertificateAuthorityID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an SSH certificate authority.
     * Delete SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesSshCertificateAuthorityIDDelete(requestParameters: ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2SshcertificateauthoritiesSshCertificateAuthorityIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get an SSH certificate authority.
     * Get SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesSshCertificateAuthorityIDGetRaw(requestParameters: ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SshCertificateAuthorityV2Read>> {
        if (requestParameters.sshCertificateAuthorityID === null || requestParameters.sshCertificateAuthorityID === undefined) {
            throw new runtime.RequiredError('sshCertificateAuthorityID','Required parameter requestParameters.sshCertificateAuthorityID was null or undefined when calling apiV2SshcertificateauthoritiesSshCertificateAuthorityIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/sshcertificateauthorities/{sshCertificateAuthorityID}`.replace(`{${"sshCertificateAuthorityID"}}`, encodeURIComponent(String(requestParameters.sshCertificateAuthorityID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SshCertificateAuthorityV2ReadFromJSON(jsonValue));
    }

    /**
     * Get an SSH certificate authority.
     * Get SSH certificate authority
     */
    async apiV2SshcertificateauthoritiesSshCertificateAuthorityIDGet(requestParameters: ApiV2SshcertificateauthoritiesSshCertificateAuthorityIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SshCertificateAuthorityV2Read> {
        const response = await this.apiV2SshcertificateauthoritiesSshCertificateAuthorityIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
