/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ModelError, VolumeV2Create, VolumeV2Read, VolumeV2Update } from '../models/index';
import {
	ModelErrorFromJSON,
	ModelErrorToJSON,
	VolumeV2CreateFromJSON,
	VolumeV2CreateToJSON,
	VolumeV2ReadFromJSON,
	VolumeV2ReadToJSON,
	VolumeV2UpdateFromJSON,
	VolumeV2UpdateToJSON
} from '../models/index';

export interface ApiV2VolumesGetRequest {
	tag?: Array<string>;
	organizationID?: Array<string>;
	projectID?: Array<string>;
	regionID?: Array<string>;
	networkID?: Array<string>;
}

export interface ApiV2VolumesPostRequest {
	volumeV2Create?: VolumeV2Create;
}

export interface ApiV2VolumesVolumeIDDeleteRequest {
	volumeID: string;
}

export interface ApiV2VolumesVolumeIDGetRequest {
	volumeID: string;
}

export interface ApiV2VolumesVolumeIDPutRequest {
	volumeID: string;
	volumeV2Update?: VolumeV2Update;
}

/**
 *
 */
export class VolumesApi extends runtime.BaseAPI {
	/**
	 * List volumes visible to the caller, optionally narrowed by scope, Region, or Network.
	 * List volumes
	 */
	async apiV2VolumesGetRaw(
		requestParameters: ApiV2VolumesGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Array<VolumeV2Read>>> {
		const queryParameters: any = {};

		if (requestParameters.tag) {
			queryParameters['tag'] = requestParameters.tag.join(runtime.COLLECTION_FORMATS['csv']);
		}

		if (requestParameters.organizationID) {
			queryParameters['organizationID'] = requestParameters.organizationID;
		}

		if (requestParameters.projectID) {
			queryParameters['projectID'] = requestParameters.projectID;
		}

		if (requestParameters.regionID) {
			queryParameters['regionID'] = requestParameters.regionID;
		}

		if (requestParameters.networkID) {
			queryParameters['networkID'] = requestParameters.networkID;
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			// oauth required
			headerParameters['Authorization'] = await this.configuration.accessToken(
				'oauth2Authentication',
				[]
			);
		}

		const response = await this.request(
			{
				path: `/api/v2/volumes`,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(VolumeV2ReadFromJSON)
		);
	}

	/**
	 * List volumes visible to the caller, optionally narrowed by scope, Region, or Network.
	 * List volumes
	 */
	async apiV2VolumesGet(
		requestParameters: ApiV2VolumesGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Array<VolumeV2Read>> {
		const response = await this.apiV2VolumesGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Create a volume on the Region and project implied by its Network. The VolumeClass and requested capacity are immutable after creation.
	 * Create volume
	 */
	async apiV2VolumesPostRaw(
		requestParameters: ApiV2VolumesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<VolumeV2Read>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			// oauth required
			headerParameters['Authorization'] = await this.configuration.accessToken(
				'oauth2Authentication',
				[]
			);
		}

		const response = await this.request(
			{
				path: `/api/v2/volumes`,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: VolumeV2CreateToJSON(requestParameters.volumeV2Create)
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => VolumeV2ReadFromJSON(jsonValue));
	}

	/**
	 * Create a volume on the Region and project implied by its Network. The VolumeClass and requested capacity are immutable after creation.
	 * Create volume
	 */
	async apiV2VolumesPost(
		requestParameters: ApiV2VolumesPostRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<VolumeV2Read> {
		const response = await this.apiV2VolumesPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Delete a volume. A volume in use must be detached before deletion.
	 * Delete volume
	 */
	async apiV2VolumesVolumeIDDeleteRaw(
		requestParameters: ApiV2VolumesVolumeIDDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters.volumeID === null || requestParameters.volumeID === undefined) {
			throw new runtime.RequiredError(
				'volumeID',
				'Required parameter requestParameters.volumeID was null or undefined when calling apiV2VolumesVolumeIDDelete.'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			// oauth required
			headerParameters['Authorization'] = await this.configuration.accessToken(
				'oauth2Authentication',
				[]
			);
		}

		const response = await this.request(
			{
				path: `/api/v2/volumes/{volumeID}`.replace(
					`{${'volumeID'}}`,
					encodeURIComponent(String(requestParameters.volumeID))
				),
				method: 'DELETE',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 * Delete a volume. A volume in use must be detached before deletion.
	 * Delete volume
	 */
	async apiV2VolumesVolumeIDDelete(
		requestParameters: ApiV2VolumesVolumeIDDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.apiV2VolumesVolumeIDDeleteRaw(requestParameters, initOverrides);
	}

	/**
	 * Get a volume, including its desired capacity and provider-observed state.
	 * Get volume
	 */
	async apiV2VolumesVolumeIDGetRaw(
		requestParameters: ApiV2VolumesVolumeIDGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<VolumeV2Read>> {
		if (requestParameters.volumeID === null || requestParameters.volumeID === undefined) {
			throw new runtime.RequiredError(
				'volumeID',
				'Required parameter requestParameters.volumeID was null or undefined when calling apiV2VolumesVolumeIDGet.'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			// oauth required
			headerParameters['Authorization'] = await this.configuration.accessToken(
				'oauth2Authentication',
				[]
			);
		}

		const response = await this.request(
			{
				path: `/api/v2/volumes/{volumeID}`.replace(
					`{${'volumeID'}}`,
					encodeURIComponent(String(requestParameters.volumeID))
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => VolumeV2ReadFromJSON(jsonValue));
	}

	/**
	 * Get a volume, including its desired capacity and provider-observed state.
	 * Get volume
	 */
	async apiV2VolumesVolumeIDGet(
		requestParameters: ApiV2VolumesVolumeIDGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<VolumeV2Read> {
		const response = await this.apiV2VolumesVolumeIDGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Update a volume\'s mutable metadata and tags.
	 * Update volume
	 */
	async apiV2VolumesVolumeIDPutRaw(
		requestParameters: ApiV2VolumesVolumeIDPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<VolumeV2Read>> {
		if (requestParameters.volumeID === null || requestParameters.volumeID === undefined) {
			throw new runtime.RequiredError(
				'volumeID',
				'Required parameter requestParameters.volumeID was null or undefined when calling apiV2VolumesVolumeIDPut.'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			// oauth required
			headerParameters['Authorization'] = await this.configuration.accessToken(
				'oauth2Authentication',
				[]
			);
		}

		const response = await this.request(
			{
				path: `/api/v2/volumes/{volumeID}`.replace(
					`{${'volumeID'}}`,
					encodeURIComponent(String(requestParameters.volumeID))
				),
				method: 'PUT',
				headers: headerParameters,
				query: queryParameters,
				body: VolumeV2UpdateToJSON(requestParameters.volumeV2Update)
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => VolumeV2ReadFromJSON(jsonValue));
	}

	/**
	 * Update a volume\'s mutable metadata and tags.
	 * Update volume
	 */
	async apiV2VolumesVolumeIDPut(
		requestParameters: ApiV2VolumesVolumeIDPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<VolumeV2Read> {
		const response = await this.apiV2VolumesVolumeIDPutRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
