/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * CPU architecture.
 * @export
 */
export const Architecture = {
    X8664: 'x86_64',
    Aarch64: 'aarch64'
} as const;
export type Architecture = typeof Architecture[keyof typeof Architecture];


export function ArchitectureFromJSON(json: any): Architecture {
    return ArchitectureFromJSONTyped(json, false);
}

export function ArchitectureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Architecture {
    return json as Architecture;
}

export function ArchitectureToJSON(value?: Architecture | null): any {
    return value as any;
}

