/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A console session response.
 * @export
 * @interface ConsoleSession
 */
export interface ConsoleSession {
    /**
     * The URL to access the console session.
     * @type {string}
     * @memberof ConsoleSession
     */
    url: string;
}

/**
 * Check if a given object implements the ConsoleSession interface.
 */
export function instanceOfConsoleSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function ConsoleSessionFromJSON(json: any): ConsoleSession {
    return ConsoleSessionFromJSONTyped(json, false);
}

export function ConsoleSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function ConsoleSessionToJSON(value?: ConsoleSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

