/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The images's lifecycle state.
 * @export
 */
export const ImageState = {
    Pending: 'pending',
    Creating: 'creating',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type ImageState = typeof ImageState[keyof typeof ImageState];


export function ImageStateFromJSON(json: any): ImageState {
    return ImageStateFromJSONTyped(json, false);
}

export function ImageStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageState {
    return json as ImageState;
}

export function ImageStateToJSON(value?: ImageState | null): any {
    return value as any;
}

