/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageState } from './ImageState';
import {
    ImageStateFromJSON,
    ImageStateFromJSONTyped,
    ImageStateToJSON,
} from './ImageState';

/**
 * The image's status.
 * @export
 * @interface ImageStatus
 */
export interface ImageStatus {
    /**
     * 
     * @type {ImageState}
     * @memberof ImageStatus
     */
    state: ImageState;
}

/**
 * Check if a given object implements the ImageStatus interface.
 */
export function instanceOfImageStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function ImageStatusFromJSON(json: any): ImageStatus {
    return ImageStatusFromJSONTyped(json, false);
}

export function ImageStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': ImageStateFromJSON(json['state']),
    };
}

export function ImageStatusToJSON(value?: ImageStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': ImageStateToJSON(value.state),
    };
}

