/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageCreateSpec } from './ImageCreateSpec';
import {
    ImageCreateSpecFromJSON,
    ImageCreateSpecFromJSONTyped,
    ImageCreateSpecToJSON,
} from './ImageCreateSpec';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A compute image create request.
 * @export
 * @interface ImageCreate
 */
export interface ImageCreate {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof ImageCreate
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {ImageCreateSpec}
     * @memberof ImageCreate
     */
    spec: ImageCreateSpec;
}

/**
 * Check if a given object implements the ImageCreate interface.
 */
export function instanceOfImageCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function ImageCreateFromJSON(json: any): ImageCreate {
    return ImageCreateFromJSONTyped(json, false);
}

export function ImageCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': ImageCreateSpecFromJSON(json['spec']),
    };
}

export function ImageCreateToJSON(value?: ImageCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': ImageCreateSpecToJSON(value.spec),
    };
}

