/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The lifecycle phase of an instance.
 * @export
 */
export const InstanceLifecyclePhase = {
    Pending: 'Pending',
    Running: 'Running',
    Stopping: 'Stopping',
    Stopped: 'Stopped'
} as const;
export type InstanceLifecyclePhase = typeof InstanceLifecyclePhase[keyof typeof InstanceLifecyclePhase];


export function InstanceLifecyclePhaseFromJSON(json: any): InstanceLifecyclePhase {
    return InstanceLifecyclePhaseFromJSONTyped(json, false);
}

export function InstanceLifecyclePhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceLifecyclePhase {
    return json as InstanceLifecyclePhase;
}

export function InstanceLifecyclePhaseToJSON(value?: InstanceLifecyclePhase | null): any {
    return value as any;
}

