/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoadBalancerHealthCheckV2 } from './LoadBalancerHealthCheckV2';
import {
    LoadBalancerHealthCheckV2FromJSON,
    LoadBalancerHealthCheckV2FromJSONTyped,
    LoadBalancerHealthCheckV2ToJSON,
} from './LoadBalancerHealthCheckV2';
import type { LoadBalancerMemberV2 } from './LoadBalancerMemberV2';
import {
    LoadBalancerMemberV2FromJSON,
    LoadBalancerMemberV2FromJSONTyped,
    LoadBalancerMemberV2ToJSON,
} from './LoadBalancerMemberV2';

/**
 * A load balancer listener pool.
 * @export
 * @interface LoadBalancerPoolV2
 */
export interface LoadBalancerPoolV2 {
    /**
     * Whether to enable Proxy Protocol v2.
     * @type {boolean}
     * @memberof LoadBalancerPoolV2
     */
    proxyProtocolV2?: boolean;
    /**
     * A list of pool members.
     * @type {Array<LoadBalancerMemberV2>}
     * @memberof LoadBalancerPoolV2
     */
    members: Array<LoadBalancerMemberV2>;
    /**
     * 
     * @type {LoadBalancerHealthCheckV2}
     * @memberof LoadBalancerPoolV2
     */
    healthCheck?: LoadBalancerHealthCheckV2;
}

/**
 * Check if a given object implements the LoadBalancerPoolV2 interface.
 */
export function instanceOfLoadBalancerPoolV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "members" in value;

    return isInstance;
}

export function LoadBalancerPoolV2FromJSON(json: any): LoadBalancerPoolV2 {
    return LoadBalancerPoolV2FromJSONTyped(json, false);
}

export function LoadBalancerPoolV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancerPoolV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'proxyProtocolV2': !exists(json, 'proxyProtocolV2') ? undefined : json['proxyProtocolV2'],
        'members': ((json['members'] as Array<any>).map(LoadBalancerMemberV2FromJSON)),
        'healthCheck': !exists(json, 'healthCheck') ? undefined : LoadBalancerHealthCheckV2FromJSON(json['healthCheck']),
    };
}

export function LoadBalancerPoolV2ToJSON(value?: LoadBalancerPoolV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'proxyProtocolV2': value.proxyProtocolV2,
        'members': ((value.members as Array<any>).map(LoadBalancerMemberV2ToJSON)),
        'healthCheck': LoadBalancerHealthCheckV2ToJSON(value.healthCheck),
    };
}

