/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Read only status information about a load balancer.
 * @export
 * @interface LoadBalancerV2Status
 */
export interface LoadBalancerV2Status {
    /**
     * The region the load balancer belongs to.
     * @type {string}
     * @memberof LoadBalancerV2Status
     */
    regionId: string;
    /**
     * The network the load balancer belongs to.
     * @type {string}
     * @memberof LoadBalancerV2Status
     */
    networkId: string;
    /**
     * An IPv4 address.
     * @type {string}
     * @memberof LoadBalancerV2Status
     */
    vipAddress?: string;
    /**
     * An IPv4 address.
     * @type {string}
     * @memberof LoadBalancerV2Status
     */
    publicIP?: string;
}

/**
 * Check if a given object implements the LoadBalancerV2Status interface.
 */
export function instanceOfLoadBalancerV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function LoadBalancerV2StatusFromJSON(json: any): LoadBalancerV2Status {
    return LoadBalancerV2StatusFromJSONTyped(json, false);
}

export function LoadBalancerV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancerV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
        'networkId': json['networkId'],
        'vipAddress': !exists(json, 'vipAddress') ? undefined : json['vipAddress'],
        'publicIP': !exists(json, 'publicIP') ? undefined : json['publicIP'],
    };
}

export function LoadBalancerV2StatusToJSON(value?: LoadBalancerV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
        'networkId': value.networkId,
        'vipAddress': value.vipAddress,
        'publicIP': value.publicIP,
    };
}

