/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoadBalancerV2Spec } from './LoadBalancerV2Spec';
import {
    LoadBalancerV2SpecFromJSON,
    LoadBalancerV2SpecFromJSONTyped,
    LoadBalancerV2SpecToJSON,
} from './LoadBalancerV2Spec';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A load balancer update request.
 * @export
 * @interface LoadBalancerV2Update
 */
export interface LoadBalancerV2Update {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof LoadBalancerV2Update
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {LoadBalancerV2Spec}
     * @memberof LoadBalancerV2Update
     */
    spec: LoadBalancerV2Spec;
}

/**
 * Check if a given object implements the LoadBalancerV2Update interface.
 */
export function instanceOfLoadBalancerV2Update(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function LoadBalancerV2UpdateFromJSON(json: any): LoadBalancerV2Update {
    return LoadBalancerV2UpdateFromJSONTyped(json, false);
}

export function LoadBalancerV2UpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancerV2Update {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': LoadBalancerV2SpecFromJSON(json['spec']),
    };
}

export function LoadBalancerV2UpdateToJSON(value?: LoadBalancerV2Update | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': LoadBalancerV2SpecToJSON(value.spec),
    };
}

