/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A load balancer pool member.
 * @export
 * @interface LoadBalancerMemberV2
 */
export interface LoadBalancerMemberV2 {
    /**
     * An IPv4 address.
     * @type {string}
     * @memberof LoadBalancerMemberV2
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof LoadBalancerMemberV2
     */
    port: number;
}

/**
 * Check if a given object implements the LoadBalancerMemberV2 interface.
 */
export function instanceOfLoadBalancerMemberV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "port" in value;

    return isInstance;
}

export function LoadBalancerMemberV2FromJSON(json: any): LoadBalancerMemberV2 {
    return LoadBalancerMemberV2FromJSONTyped(json, false);
}

export function LoadBalancerMemberV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancerMemberV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'port': json['port'],
    };
}

export function LoadBalancerMemberV2ToJSON(value?: LoadBalancerMemberV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'port': value.port,
    };
}

