/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A load balancer pool health check.
 * @export
 * @interface LoadBalancerHealthCheckV2
 */
export interface LoadBalancerHealthCheckV2 {
    /**
     * 
     * @type {number}
     * @memberof LoadBalancerHealthCheckV2
     */
    intervalSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadBalancerHealthCheckV2
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadBalancerHealthCheckV2
     */
    healthyThreshold?: number;
    /**
     * 
     * @type {number}
     * @memberof LoadBalancerHealthCheckV2
     */
    unhealthyThreshold?: number;
}

/**
 * Check if a given object implements the LoadBalancerHealthCheckV2 interface.
 */
export function instanceOfLoadBalancerHealthCheckV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoadBalancerHealthCheckV2FromJSON(json: any): LoadBalancerHealthCheckV2 {
    return LoadBalancerHealthCheckV2FromJSONTyped(json, false);
}

export function LoadBalancerHealthCheckV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancerHealthCheckV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'intervalSeconds': !exists(json, 'intervalSeconds') ? undefined : json['intervalSeconds'],
        'timeoutSeconds': !exists(json, 'timeoutSeconds') ? undefined : json['timeoutSeconds'],
        'healthyThreshold': !exists(json, 'healthyThreshold') ? undefined : json['healthyThreshold'],
        'unhealthyThreshold': !exists(json, 'unhealthyThreshold') ? undefined : json['unhealthyThreshold'],
    };
}

export function LoadBalancerHealthCheckV2ToJSON(value?: LoadBalancerHealthCheckV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'intervalSeconds': value.intervalSeconds,
        'timeoutSeconds': value.timeoutSeconds,
        'healthyThreshold': value.healthyThreshold,
        'unhealthyThreshold': value.unhealthyThreshold,
    };
}

