/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Route } from './Route';
import {
    RouteFromJSON,
    RouteFromJSONTyped,
    RouteToJSON,
} from './Route';

/**
 * A network's specification.
 * @export
 * @interface NetworkV2CreateSpec
 */
export interface NetworkV2CreateSpec {
    /**
     * A list of IPv4 addresses.
     * @type {Array<string>}
     * @memberof NetworkV2CreateSpec
     */
    dnsNameservers: Array<string>;
    /**
     * A list of network routes.
     * @type {Array<Route>}
     * @memberof NetworkV2CreateSpec
     */
    routes?: Array<Route>;
    /**
     * The organization to provision the resource in.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    organizationId: string;
    /**
     * The project to provision the resource in.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    projectId: string;
    /**
     * The region a network is to be provisioned in.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    regionId: string;
    /**
     * An IPv4 prefix for the network.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    prefix: string;
}

/**
 * Check if a given object implements the NetworkV2CreateSpec interface.
 */
export function instanceOfNetworkV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dnsNameservers" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "prefix" in value;

    return isInstance;
}

export function NetworkV2CreateSpecFromJSON(json: any): NetworkV2CreateSpec {
    return NetworkV2CreateSpecFromJSONTyped(json, false);
}

export function NetworkV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dnsNameservers': json['dnsNameservers'],
        'routes': !exists(json, 'routes') ? undefined : ((json['routes'] as Array<any>).map(RouteFromJSON)),
        'organizationId': json['organizationId'],
        'projectId': json['projectId'],
        'regionId': json['regionId'],
        'prefix': json['prefix'],
    };
}

export function NetworkV2CreateSpecToJSON(value?: NetworkV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dnsNameservers': value.dnsNameservers,
        'routes': value.routes === undefined ? undefined : ((value.routes as Array<any>).map(RouteToJSON)),
        'organizationId': value.organizationId,
        'projectId': value.projectId,
        'regionId': value.regionId,
        'prefix': value.prefix,
    };
}

