/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NetworkV2Spec } from './NetworkV2Spec';
import {
    NetworkV2SpecFromJSON,
    NetworkV2SpecFromJSONTyped,
    NetworkV2SpecToJSON,
} from './NetworkV2Spec';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A network request.
 * @export
 * @interface NetworkV2Update
 */
export interface NetworkV2Update {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof NetworkV2Update
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {NetworkV2Spec}
     * @memberof NetworkV2Update
     */
    spec: NetworkV2Spec;
}

/**
 * Check if a given object implements the NetworkV2Update interface.
 */
export function instanceOfNetworkV2Update(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function NetworkV2UpdateFromJSON(json: any): NetworkV2Update {
    return NetworkV2UpdateFromJSONTyped(json, false);
}

export function NetworkV2UpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkV2Update {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': NetworkV2SpecFromJSON(json['spec']),
    };
}

export function NetworkV2UpdateToJSON(value?: NetworkV2Update | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': NetworkV2SpecToJSON(value.spec),
    };
}

