/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NetworkV2CreateSpec } from './NetworkV2CreateSpec';
import {
    NetworkV2CreateSpecFromJSON,
    NetworkV2CreateSpecFromJSONTyped,
    NetworkV2CreateSpecToJSON,
} from './NetworkV2CreateSpec';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A network request.
 * @export
 * @interface NetworkV2Create
 */
export interface NetworkV2Create {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof NetworkV2Create
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {NetworkV2CreateSpec}
     * @memberof NetworkV2Create
     */
    spec: NetworkV2CreateSpec;
}

/**
 * Check if a given object implements the NetworkV2Create interface.
 */
export function instanceOfNetworkV2Create(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function NetworkV2CreateFromJSON(json: any): NetworkV2Create {
    return NetworkV2CreateFromJSONTyped(json, false);
}

export function NetworkV2CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkV2Create {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': NetworkV2CreateSpecFromJSON(json['spec']),
    };
}

export function NetworkV2CreateToJSON(value?: NetworkV2Create | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': NetworkV2CreateSpecToJSON(value.spec),
    };
}

