/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A network's specification.
 * @export
 * @interface NetworkV2CreateSpec
 */
export interface NetworkV2CreateSpec {
    /**
     * An IPv4 prefix for the network.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    prefix: string;
    /**
     * A list of IPv4 addresses.
     * @type {Array<string>}
     * @memberof NetworkV2CreateSpec
     */
    dnsNameservers: Array<string>;
    /**
     * The region a network is to be provisioned in.
     * @type {string}
     * @memberof NetworkV2CreateSpec
     */
    regionId: string;
}

/**
 * Check if a given object implements the NetworkV2CreateSpec interface.
 */
export function instanceOfNetworkV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prefix" in value;
    isInstance = isInstance && "dnsNameservers" in value;
    isInstance = isInstance && "regionId" in value;

    return isInstance;
}

export function NetworkV2CreateSpecFromJSON(json: any): NetworkV2CreateSpec {
    return NetworkV2CreateSpecFromJSONTyped(json, false);
}

export function NetworkV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prefix': json['prefix'],
        'dnsNameservers': json['dnsNameservers'],
        'regionId': json['regionId'],
    };
}

export function NetworkV2CreateSpecToJSON(value?: NetworkV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prefix': value.prefix,
        'dnsNameservers': value.dnsNameservers,
        'regionId': value.regionId,
    };
}

