/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';
import type { SecurityGroupV2Spec } from './SecurityGroupV2Spec';
import {
    SecurityGroupV2SpecFromJSON,
    SecurityGroupV2SpecFromJSONTyped,
    SecurityGroupV2SpecToJSON,
} from './SecurityGroupV2Spec';
import type { SecurityGroupV2Status } from './SecurityGroupV2Status';
import {
    SecurityGroupV2StatusFromJSON,
    SecurityGroupV2StatusFromJSONTyped,
    SecurityGroupV2StatusToJSON,
} from './SecurityGroupV2Status';

/**
 * A security group.
 * @export
 * @interface SecurityGroupV2Read
 */
export interface SecurityGroupV2Read {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof SecurityGroupV2Read
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {SecurityGroupV2Spec}
     * @memberof SecurityGroupV2Read
     */
    spec: SecurityGroupV2Spec;
    /**
     * 
     * @type {SecurityGroupV2Status}
     * @memberof SecurityGroupV2Read
     */
    status: SecurityGroupV2Status;
}

/**
 * Check if a given object implements the SecurityGroupV2Read interface.
 */
export function instanceOfSecurityGroupV2Read(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function SecurityGroupV2ReadFromJSON(json: any): SecurityGroupV2Read {
    return SecurityGroupV2ReadFromJSONTyped(json, false);
}

export function SecurityGroupV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityGroupV2Read {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': SecurityGroupV2SpecFromJSON(json['spec']),
        'status': SecurityGroupV2StatusFromJSON(json['status']),
    };
}

export function SecurityGroupV2ReadToJSON(value?: SecurityGroupV2Read | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': SecurityGroupV2SpecToJSON(value.spec),
        'status': SecurityGroupV2StatusToJSON(value.status),
    };
}

