/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SecurityGroupRuleV2 } from './SecurityGroupRuleV2';
import {
    SecurityGroupRuleV2FromJSON,
    SecurityGroupRuleV2FromJSONTyped,
    SecurityGroupRuleV2ToJSON,
} from './SecurityGroupRuleV2';

/**
 * A security group's specification.
 * @export
 * @interface SecurityGroupV2Spec
 */
export interface SecurityGroupV2Spec {
    /**
     * A set of security group rules to apply.
     * @type {Array<SecurityGroupRuleV2>}
     * @memberof SecurityGroupV2Spec
     */
    rules: Array<SecurityGroupRuleV2>;
}

/**
 * Check if a given object implements the SecurityGroupV2Spec interface.
 */
export function instanceOfSecurityGroupV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rules" in value;

    return isInstance;
}

export function SecurityGroupV2SpecFromJSON(json: any): SecurityGroupV2Spec {
    return SecurityGroupV2SpecFromJSONTyped(json, false);
}

export function SecurityGroupV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityGroupV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(SecurityGroupRuleV2FromJSON)),
    };
}

export function SecurityGroupV2SpecToJSON(value?: SecurityGroupV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rules': ((value.rules as Array<any>).map(SecurityGroupRuleV2ToJSON)),
    };
}

