/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NetworkDirection } from './NetworkDirection';
import {
    NetworkDirectionFromJSON,
    NetworkDirectionFromJSONTyped,
    NetworkDirectionToJSON,
} from './NetworkDirection';
import type { NetworkProtocol } from './NetworkProtocol';
import {
    NetworkProtocolFromJSON,
    NetworkProtocolFromJSONTyped,
    NetworkProtocolToJSON,
} from './NetworkProtocol';

/**
 * A security group rule's specification, this operates at OSI layer 3 and above.
 * If omitted the prefix defaults to 0.0.0.0/0 e.g. allow from anywhere.
 * @export
 * @interface SecurityGroupRuleV2
 */
export interface SecurityGroupRuleV2 {
    /**
     * 
     * @type {NetworkDirection}
     * @memberof SecurityGroupRuleV2
     */
    direction: NetworkDirection;
    /**
     * 
     * @type {NetworkProtocol}
     * @memberof SecurityGroupRuleV2
     */
    protocol: NetworkProtocol;
    /**
     * Port number for layer 4 protocols, if not specified matches all ports.
     * @type {number}
     * @memberof SecurityGroupRuleV2
     */
    port?: number;
    /**
     * maxumum port number for layer 4 protocols to include a range.
     * @type {number}
     * @memberof SecurityGroupRuleV2
     */
    portMax?: number;
    /**
     * An IPv4 address.
     * @type {string}
     * @memberof SecurityGroupRuleV2
     */
    prefix?: string;
}

/**
 * Check if a given object implements the SecurityGroupRuleV2 interface.
 */
export function instanceOfSecurityGroupRuleV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "direction" in value;
    isInstance = isInstance && "protocol" in value;

    return isInstance;
}

export function SecurityGroupRuleV2FromJSON(json: any): SecurityGroupRuleV2 {
    return SecurityGroupRuleV2FromJSONTyped(json, false);
}

export function SecurityGroupRuleV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityGroupRuleV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'direction': NetworkDirectionFromJSON(json['direction']),
        'protocol': NetworkProtocolFromJSON(json['protocol']),
        'port': !exists(json, 'port') ? undefined : json['port'],
        'portMax': !exists(json, 'portMax') ? undefined : json['portMax'],
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
    };
}

export function SecurityGroupRuleV2ToJSON(value?: SecurityGroupRuleV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'direction': NetworkDirectionToJSON(value.direction),
        'protocol': NetworkProtocolToJSON(value.protocol),
        'port': value.port,
        'portMax': value.portMax,
        'prefix': value.prefix,
    };
}

