/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SecurityGroupRuleV2 } from './SecurityGroupRuleV2';
import {
    SecurityGroupRuleV2FromJSON,
    SecurityGroupRuleV2FromJSONTyped,
    SecurityGroupRuleV2ToJSON,
} from './SecurityGroupRuleV2';

/**
 * A security group's specification.
 * @export
 * @interface SecurityGroupV2CreateSpec
 */
export interface SecurityGroupV2CreateSpec {
    /**
     * A set of security group rules to apply.
     * @type {Array<SecurityGroupRuleV2>}
     * @memberof SecurityGroupV2CreateSpec
     */
    rules: Array<SecurityGroupRuleV2>;
    /**
     * The network a security group belongs to.
     * @type {string}
     * @memberof SecurityGroupV2CreateSpec
     */
    networkId: string;
}

/**
 * Check if a given object implements the SecurityGroupV2CreateSpec interface.
 */
export function instanceOfSecurityGroupV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rules" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function SecurityGroupV2CreateSpecFromJSON(json: any): SecurityGroupV2CreateSpec {
    return SecurityGroupV2CreateSpecFromJSONTyped(json, false);
}

export function SecurityGroupV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityGroupV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(SecurityGroupRuleV2FromJSON)),
        'networkId': json['networkId'],
    };
}

export function SecurityGroupV2CreateSpecToJSON(value?: SecurityGroupV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rules': ((value.rules as Array<any>).map(SecurityGroupRuleV2ToJSON)),
        'networkId': value.networkId,
    };
}

