/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { ServerV2Spec } from './ServerV2Spec';
import {
    ServerV2SpecFromJSON,
    ServerV2SpecFromJSONTyped,
    ServerV2SpecToJSON,
} from './ServerV2Spec';

/**
 * A server update request.
 * @export
 * @interface ServerV2Update
 */
export interface ServerV2Update {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof ServerV2Update
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {ServerV2Spec}
     * @memberof ServerV2Update
     */
    spec: ServerV2Spec;
}

/**
 * Check if a given object implements the ServerV2Update interface.
 */
export function instanceOfServerV2Update(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function ServerV2UpdateFromJSON(json: any): ServerV2Update {
    return ServerV2UpdateFromJSONTyped(json, false);
}

export function ServerV2UpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2Update {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': ServerV2SpecFromJSON(json['spec']),
    };
}

export function ServerV2UpdateToJSON(value?: ServerV2Update | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': ServerV2SpecToJSON(value.spec),
    };
}

