/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A server's network configuration.
 * @export
 * @interface ServerV2Networking
 */
export interface ServerV2Networking {
    /**
     * A list of security group IDs.
     * @type {Array<string>}
     * @memberof ServerV2Networking
     */
    securityGroups?: Array<string>;
    /**
     * Whether or not to provision a public IP.
     * @type {boolean}
     * @memberof ServerV2Networking
     */
    publicIP?: boolean;
    /**
     * A list of network prefixes that are allowed to egress from the server.
     * By default, only packets from the server's network interface's IP address
     * are allowed to enter the network.  Use of this option allows the server
     * to act as a router without SNAT rules.
     * @type {Array<string>}
     * @memberof ServerV2Networking
     */
    allowedSourceAddresses?: Array<string>;
}

/**
 * Check if a given object implements the ServerV2Networking interface.
 */
export function instanceOfServerV2Networking(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServerV2NetworkingFromJSON(json: any): ServerV2Networking {
    return ServerV2NetworkingFromJSONTyped(json, false);
}

export function ServerV2NetworkingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2Networking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'securityGroups': !exists(json, 'securityGroups') ? undefined : json['securityGroups'],
        'publicIP': !exists(json, 'publicIP') ? undefined : json['publicIP'],
        'allowedSourceAddresses': !exists(json, 'allowedSourceAddresses') ? undefined : json['allowedSourceAddresses'],
    };
}

export function ServerV2NetworkingToJSON(value?: ServerV2Networking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'securityGroups': value.securityGroups,
        'publicIP': value.publicIP,
        'allowedSourceAddresses': value.allowedSourceAddresses,
    };
}

