/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceLifecyclePhase } from './InstanceLifecyclePhase';
import {
    InstanceLifecyclePhaseFromJSON,
    InstanceLifecyclePhaseFromJSONTyped,
    InstanceLifecyclePhaseToJSON,
} from './InstanceLifecyclePhase';

/**
 * Read only status information about a security group.
 * @export
 * @interface ServerV2Status
 */
export interface ServerV2Status {
    /**
     * The region a security group belongs to.
     * @type {string}
     * @memberof ServerV2Status
     */
    regionId: string;
    /**
     * The network a security group belongs to.
     * @type {string}
     * @memberof ServerV2Status
     */
    networkId: string;
    /**
     * 
     * @type {InstanceLifecyclePhase}
     * @memberof ServerV2Status
     */
    powerState?: InstanceLifecyclePhase;
    /**
     * The private IP address of the server.
     * @type {string}
     * @memberof ServerV2Status
     */
    privateIP?: string;
    /**
     * The public IP address of the server.
     * @type {string}
     * @memberof ServerV2Status
     */
    publicIP?: string;
}

/**
 * Check if a given object implements the ServerV2Status interface.
 */
export function instanceOfServerV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function ServerV2StatusFromJSON(json: any): ServerV2Status {
    return ServerV2StatusFromJSONTyped(json, false);
}

export function ServerV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
        'networkId': json['networkId'],
        'powerState': !exists(json, 'powerState') ? undefined : InstanceLifecyclePhaseFromJSON(json['powerState']),
        'privateIP': !exists(json, 'privateIP') ? undefined : json['privateIP'],
        'publicIP': !exists(json, 'publicIP') ? undefined : json['publicIP'],
    };
}

export function ServerV2StatusToJSON(value?: ServerV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
        'networkId': value.networkId,
        'powerState': InstanceLifecyclePhaseToJSON(value.powerState),
        'privateIP': value.privateIP,
        'publicIP': value.publicIP,
    };
}

