/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';
import type { ServerV2Spec } from './ServerV2Spec';
import {
    ServerV2SpecFromJSON,
    ServerV2SpecFromJSONTyped,
    ServerV2SpecToJSON,
} from './ServerV2Spec';
import type { ServerV2Status } from './ServerV2Status';
import {
    ServerV2StatusFromJSON,
    ServerV2StatusFromJSONTyped,
    ServerV2StatusToJSON,
} from './ServerV2Status';

/**
 * A server.
 * @export
 * @interface ServerV2Read
 */
export interface ServerV2Read {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof ServerV2Read
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {ServerV2Spec}
     * @memberof ServerV2Read
     */
    spec: ServerV2Spec;
    /**
     * 
     * @type {ServerV2Status}
     * @memberof ServerV2Read
     */
    status: ServerV2Status;
}

/**
 * Check if a given object implements the ServerV2Read interface.
 */
export function instanceOfServerV2Read(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ServerV2ReadFromJSON(json: any): ServerV2Read {
    return ServerV2ReadFromJSONTyped(json, false);
}

export function ServerV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2Read {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': ServerV2SpecFromJSON(json['spec']),
        'status': ServerV2StatusFromJSON(json['status']),
    };
}

export function ServerV2ReadToJSON(value?: ServerV2Read | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': ServerV2SpecToJSON(value.spec),
        'status': ServerV2StatusToJSON(value.status),
    };
}

