/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { ServerV2CreateSpec } from './ServerV2CreateSpec';
import {
    ServerV2CreateSpecFromJSON,
    ServerV2CreateSpecFromJSONTyped,
    ServerV2CreateSpecToJSON,
} from './ServerV2CreateSpec';

/**
 * A server creation request.
 * @export
 * @interface ServerV2Create
 */
export interface ServerV2Create {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof ServerV2Create
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {ServerV2CreateSpec}
     * @memberof ServerV2Create
     */
    spec: ServerV2CreateSpec;
}

/**
 * Check if a given object implements the ServerV2Create interface.
 */
export function instanceOfServerV2Create(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function ServerV2CreateFromJSON(json: any): ServerV2Create {
    return ServerV2CreateFromJSONTyped(json, false);
}

export function ServerV2CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2Create {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': ServerV2CreateSpecFromJSON(json['spec']),
    };
}

export function ServerV2CreateToJSON(value?: ServerV2Create | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': ServerV2CreateSpecToJSON(value.spec),
    };
}

