/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ServerV2Networking } from './ServerV2Networking';
import {
    ServerV2NetworkingFromJSON,
    ServerV2NetworkingFromJSONTyped,
    ServerV2NetworkingToJSON,
} from './ServerV2Networking';

/**
 * A server's specification.
 * @export
 * @interface ServerV2CreateSpec
 */
export interface ServerV2CreateSpec {
    /**
     * The flavor of the server.
     * @type {string}
     * @memberof ServerV2CreateSpec
     */
    flavorId: string;
    /**
     * The image of the server.
     * @type {string}
     * @memberof ServerV2CreateSpec
     */
    imageId: string;
    /**
     * 
     * @type {ServerV2Networking}
     * @memberof ServerV2CreateSpec
     */
    networking?: ServerV2Networking;
    /**
     * Contains base64-encoded configuration information or scripts to use upon launch.
     * The format of the data is governed by the cloud-init standard, and may be a script,
     * a MIME multipart archive, etc.
     * @type {string}
     * @memberof ServerV2CreateSpec
     */
    userData?: string;
    /**
     * The network ID to attach a server to.
     * @type {string}
     * @memberof ServerV2CreateSpec
     */
    networkId: string;
}

/**
 * Check if a given object implements the ServerV2CreateSpec interface.
 */
export function instanceOfServerV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "flavorId" in value;
    isInstance = isInstance && "imageId" in value;
    isInstance = isInstance && "networkId" in value;

    return isInstance;
}

export function ServerV2CreateSpecFromJSON(json: any): ServerV2CreateSpec {
    return ServerV2CreateSpecFromJSONTyped(json, false);
}

export function ServerV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flavorId': json['flavorId'],
        'imageId': json['imageId'],
        'networking': !exists(json, 'networking') ? undefined : ServerV2NetworkingFromJSON(json['networking']),
        'userData': !exists(json, 'userData') ? undefined : json['userData'],
        'networkId': json['networkId'],
    };
}

export function ServerV2CreateSpecToJSON(value?: ServerV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flavorId': value.flavorId,
        'imageId': value.imageId,
        'networking': ServerV2NetworkingToJSON(value.networking),
        'userData': value.userData,
        'networkId': value.networkId,
    };
}

