/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';

/**
 * A compute image create request.
 * @export
 * @interface SnapshotCreate
 */
export interface SnapshotCreate {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof SnapshotCreate
     */
    metadata: ResourceWriteMetadata;
    /**
     * A compute image snapshot specification.
     * @type {object}
     * @memberof SnapshotCreate
     */
    spec: object;
}

/**
 * Check if a given object implements the SnapshotCreate interface.
 */
export function instanceOfSnapshotCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function SnapshotCreateFromJSON(json: any): SnapshotCreate {
    return SnapshotCreateFromJSONTyped(json, false);
}

export function SnapshotCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': json['spec'],
    };
}

export function SnapshotCreateToJSON(value?: SnapshotCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': value.spec,
    };
}

