/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An SSH certificate authority creation specification.
 * @export
 * @interface SshCertificateAuthorityV2CreateSpec
 */
export interface SshCertificateAuthorityV2CreateSpec {
    /**
     * A single-line OpenSSH-formatted CA public key.
     * @type {string}
     * @memberof SshCertificateAuthorityV2CreateSpec
     */
    publicKey: string;
    /**
     * The organization the SSH certificate authority belongs to.
     * @type {string}
     * @memberof SshCertificateAuthorityV2CreateSpec
     */
    organizationId: string;
    /**
     * The project the SSH certificate authority belongs to.
     * @type {string}
     * @memberof SshCertificateAuthorityV2CreateSpec
     */
    projectId: string;
}

/**
 * Check if a given object implements the SshCertificateAuthorityV2CreateSpec interface.
 */
export function instanceOfSshCertificateAuthorityV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "publicKey" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function SshCertificateAuthorityV2CreateSpecFromJSON(json: any): SshCertificateAuthorityV2CreateSpec {
    return SshCertificateAuthorityV2CreateSpecFromJSONTyped(json, false);
}

export function SshCertificateAuthorityV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshCertificateAuthorityV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': json['publicKey'],
        'organizationId': json['organizationId'],
        'projectId': json['projectId'],
    };
}

export function SshCertificateAuthorityV2CreateSpecToJSON(value?: SshCertificateAuthorityV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
        'organizationId': value.organizationId,
        'projectId': value.projectId,
    };
}

