/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An OpenSSH user certificate authority trust anchor.
 * @export
 * @interface SshCertificateAuthorityV2Spec
 */
export interface SshCertificateAuthorityV2Spec {
    /**
     * A single-line OpenSSH-formatted CA public key.
     * @type {string}
     * @memberof SshCertificateAuthorityV2Spec
     */
    publicKey: string;
}

/**
 * Check if a given object implements the SshCertificateAuthorityV2Spec interface.
 */
export function instanceOfSshCertificateAuthorityV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "publicKey" in value;

    return isInstance;
}

export function SshCertificateAuthorityV2SpecFromJSON(json: any): SshCertificateAuthorityV2Spec {
    return SshCertificateAuthorityV2SpecFromJSONTyped(json, false);
}

export function SshCertificateAuthorityV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshCertificateAuthorityV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': json['publicKey'],
    };
}

export function SshCertificateAuthorityV2SpecToJSON(value?: SshCertificateAuthorityV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
    };
}

