/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';
import type { SshCertificateAuthorityV2Spec } from './SshCertificateAuthorityV2Spec';
import {
    SshCertificateAuthorityV2SpecFromJSON,
    SshCertificateAuthorityV2SpecFromJSONTyped,
    SshCertificateAuthorityV2SpecToJSON,
} from './SshCertificateAuthorityV2Spec';

/**
 * An SSH certificate authority.
 * @export
 * @interface SshCertificateAuthorityV2Read
 */
export interface SshCertificateAuthorityV2Read {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof SshCertificateAuthorityV2Read
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {SshCertificateAuthorityV2Spec}
     * @memberof SshCertificateAuthorityV2Read
     */
    spec: SshCertificateAuthorityV2Spec;
}

/**
 * Check if a given object implements the SshCertificateAuthorityV2Read interface.
 */
export function instanceOfSshCertificateAuthorityV2Read(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function SshCertificateAuthorityV2ReadFromJSON(json: any): SshCertificateAuthorityV2Read {
    return SshCertificateAuthorityV2ReadFromJSONTyped(json, false);
}

export function SshCertificateAuthorityV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshCertificateAuthorityV2Read {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': SshCertificateAuthorityV2SpecFromJSON(json['spec']),
    };
}

export function SshCertificateAuthorityV2ReadToJSON(value?: SshCertificateAuthorityV2Read | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': SshCertificateAuthorityV2SpecToJSON(value.spec),
    };
}

