/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { SshCertificateAuthorityV2CreateSpec } from './SshCertificateAuthorityV2CreateSpec';
import {
    SshCertificateAuthorityV2CreateSpecFromJSON,
    SshCertificateAuthorityV2CreateSpecFromJSONTyped,
    SshCertificateAuthorityV2CreateSpecToJSON,
} from './SshCertificateAuthorityV2CreateSpec';

/**
 * An SSH certificate authority creation request.
 * @export
 * @interface SshCertificateAuthorityV2Create
 */
export interface SshCertificateAuthorityV2Create {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof SshCertificateAuthorityV2Create
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {SshCertificateAuthorityV2CreateSpec}
     * @memberof SshCertificateAuthorityV2Create
     */
    spec: SshCertificateAuthorityV2CreateSpec;
}

/**
 * Check if a given object implements the SshCertificateAuthorityV2Create interface.
 */
export function instanceOfSshCertificateAuthorityV2Create(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function SshCertificateAuthorityV2CreateFromJSON(json: any): SshCertificateAuthorityV2Create {
    return SshCertificateAuthorityV2CreateFromJSONTyped(json, false);
}

export function SshCertificateAuthorityV2CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshCertificateAuthorityV2Create {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': SshCertificateAuthorityV2CreateSpecFromJSON(json['spec']),
    };
}

export function SshCertificateAuthorityV2CreateToJSON(value?: SshCertificateAuthorityV2Create | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': SshCertificateAuthorityV2CreateSpecToJSON(value.spec),
    };
}

