/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An SSH key.
 * @export
 * @interface SshKey
 */
export interface SshKey {
    /**
     * The SSH private key.
     * @type {string}
     * @memberof SshKey
     */
    privateKey: string;
}

/**
 * Check if a given object implements the SshKey interface.
 */
export function instanceOfSshKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "privateKey" in value;

    return isInstance;
}

export function SshKeyFromJSON(json: any): SshKey {
    return SshKeyFromJSONTyped(json, false);
}

export function SshKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'privateKey': json['privateKey'],
    };
}

export function SshKeyToJSON(value?: SshKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'privateKey': value.privateKey,
    };
}

