/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageClassProtocolType } from './StorageClassProtocolType';
import {
    StorageClassProtocolTypeFromJSON,
    StorageClassProtocolTypeFromJSONTyped,
    StorageClassProtocolTypeToJSON,
} from './StorageClassProtocolType';

/**
 * A storage class's specification.
 * @export
 * @interface StorageClassV2Spec
 */
export interface StorageClassV2Spec {
    /**
     * The region an storage class is provisioned in.
     * @type {string}
     * @memberof StorageClassV2Spec
     */
    regionId: string;
    /**
     * 
     * @type {Array<StorageClassProtocolType>}
     * @memberof StorageClassV2Spec
     */
    protocols: Array<StorageClassProtocolType>;
}

/**
 * Check if a given object implements the StorageClassV2Spec interface.
 */
export function instanceOfStorageClassV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "protocols" in value;

    return isInstance;
}

export function StorageClassV2SpecFromJSON(json: any): StorageClassV2Spec {
    return StorageClassV2SpecFromJSONTyped(json, false);
}

export function StorageClassV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageClassV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
        'protocols': ((json['protocols'] as Array<any>).map(StorageClassProtocolTypeFromJSON)),
    };
}

export function StorageClassV2SpecToJSON(value?: StorageClassV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
        'protocols': ((value.protocols as Array<any>).map(StorageClassProtocolTypeToJSON)),
    };
}

