/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceProvisioningStatus } from './ResourceProvisioningStatus';
import {
    ResourceProvisioningStatusFromJSON,
    ResourceProvisioningStatusFromJSONTyped,
    ResourceProvisioningStatusToJSON,
} from './ResourceProvisioningStatus';

/**
 * Describes the network attachment for storage
 * @export
 * @interface StorageAttachmentV2Status
 */
export interface StorageAttachmentV2Status {
    /**
     * The network ID
     * @type {string}
     * @memberof StorageAttachmentV2Status
     */
    networkId: string;
    /**
     * The mount source for the attached storage in the format <host>:<path>.
     * @type {string}
     * @memberof StorageAttachmentV2Status
     */
    mountSource?: string;
    /**
     * 
     * @type {ResourceProvisioningStatus}
     * @memberof StorageAttachmentV2Status
     */
    provisioningStatus: ResourceProvisioningStatus;
}

/**
 * Check if a given object implements the StorageAttachmentV2Status interface.
 */
export function instanceOfStorageAttachmentV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "networkId" in value;
    isInstance = isInstance && "provisioningStatus" in value;

    return isInstance;
}

export function StorageAttachmentV2StatusFromJSON(json: any): StorageAttachmentV2Status {
    return StorageAttachmentV2StatusFromJSONTyped(json, false);
}

export function StorageAttachmentV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAttachmentV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'networkId': json['networkId'],
        'mountSource': !exists(json, 'mountSource') ? undefined : json['mountSource'],
        'provisioningStatus': ResourceProvisioningStatusFromJSON(json['provisioningStatus']),
    };
}

export function StorageAttachmentV2StatusToJSON(value?: StorageAttachmentV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'networkId': value.networkId,
        'mountSource': value.mountSource,
        'provisioningStatus': ResourceProvisioningStatusToJSON(value.provisioningStatus),
    };
}

