/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageAttachmentV2SpecNetworkIdsInner
 */
export interface StorageAttachmentV2SpecNetworkIdsInner {
    /**
     * 
     * @type {string}
     * @memberof StorageAttachmentV2SpecNetworkIdsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the StorageAttachmentV2SpecNetworkIdsInner interface.
 */
export function instanceOfStorageAttachmentV2SpecNetworkIdsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageAttachmentV2SpecNetworkIdsInnerFromJSON(json: any): StorageAttachmentV2SpecNetworkIdsInner {
    return StorageAttachmentV2SpecNetworkIdsInnerFromJSONTyped(json, false);
}

export function StorageAttachmentV2SpecNetworkIdsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAttachmentV2SpecNetworkIdsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function StorageAttachmentV2SpecNetworkIdsInnerToJSON(value?: StorageAttachmentV2SpecNetworkIdsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

