/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The protocol type of the storage class.
 * @export
 */
export const StorageClassProtocolType = {
    Nfsv3: 'nfsv3',
    Nfsv4: 'nfsv4'
} as const;
export type StorageClassProtocolType = typeof StorageClassProtocolType[keyof typeof StorageClassProtocolType];


export function StorageClassProtocolTypeFromJSON(json: any): StorageClassProtocolType {
    return StorageClassProtocolTypeFromJSONTyped(json, false);
}

export function StorageClassProtocolTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageClassProtocolType {
    return json as StorageClassProtocolType;
}

export function StorageClassProtocolTypeToJSON(value?: StorageClassProtocolType | null): any {
    return value as any;
}

