/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes the network attachment for storage
 * @export
 * @interface StorageAttachmentV2Spec
 */
export interface StorageAttachmentV2Spec {
    /**
     * A list of network IDs
     * @type {Array<string>}
     * @memberof StorageAttachmentV2Spec
     */
    networkIDs: Array<string>;
}

/**
 * Check if a given object implements the StorageAttachmentV2Spec interface.
 */
export function instanceOfStorageAttachmentV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "networkIDs" in value;

    return isInstance;
}

export function StorageAttachmentV2SpecFromJSON(json: any): StorageAttachmentV2Spec {
    return StorageAttachmentV2SpecFromJSONTyped(json, false);
}

export function StorageAttachmentV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAttachmentV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'networkIDs': json['networkIDs'],
    };
}

export function StorageAttachmentV2SpecToJSON(value?: StorageAttachmentV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'networkIDs': value.networkIDs,
    };
}

