/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';
import type { StorageV2Spec } from './StorageV2Spec';
import {
    StorageV2SpecFromJSON,
    StorageV2SpecFromJSONTyped,
    StorageV2SpecToJSON,
} from './StorageV2Spec';
import type { StorageV2Status } from './StorageV2Status';
import {
    StorageV2StatusFromJSON,
    StorageV2StatusFromJSONTyped,
    StorageV2StatusToJSON,
} from './StorageV2Status';

/**
 * A storage read only group.
 * @export
 * @interface StorageV2Read
 */
export interface StorageV2Read {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof StorageV2Read
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {StorageV2Spec}
     * @memberof StorageV2Read
     */
    spec: StorageV2Spec;
    /**
     * 
     * @type {StorageV2Status}
     * @memberof StorageV2Read
     */
    status: StorageV2Status;
}

/**
 * Check if a given object implements the StorageV2Read interface.
 */
export function instanceOfStorageV2Read(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function StorageV2ReadFromJSON(json: any): StorageV2Read {
    return StorageV2ReadFromJSONTyped(json, false);
}

export function StorageV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2Read {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': StorageV2SpecFromJSON(json['spec']),
        'status': StorageV2StatusFromJSON(json['status']),
    };
}

export function StorageV2ReadToJSON(value?: StorageV2Read | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': StorageV2SpecToJSON(value.spec),
        'status': StorageV2StatusToJSON(value.status),
    };
}

