/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageAttachmentV2Status } from './StorageAttachmentV2Status';
import {
    StorageAttachmentV2StatusFromJSON,
    StorageAttachmentV2StatusFromJSONTyped,
    StorageAttachmentV2StatusToJSON,
} from './StorageAttachmentV2Status';
import type { StorageUsageV2Status } from './StorageUsageV2Status';
import {
    StorageUsageV2StatusFromJSON,
    StorageUsageV2StatusFromJSONTyped,
    StorageUsageV2StatusToJSON,
} from './StorageUsageV2Status';

/**
 * Read only status about storage
 * @export
 * @interface StorageV2Status
 */
export interface StorageV2Status {
    /**
     * identifier for the storage
     * @type {string}
     * @memberof StorageV2Status
     */
    storageClassId: string;
    /**
     * The region an identity is provisioned in.
     * @type {string}
     * @memberof StorageV2Status
     */
    regionId: string;
    /**
     * 
     * @type {StorageUsageV2Status}
     * @memberof StorageV2Status
     */
    usage?: StorageUsageV2Status;
    /**
     * Describes the network attachments for storage
     * @type {Array<StorageAttachmentV2Status>}
     * @memberof StorageV2Status
     */
    attachments?: Array<StorageAttachmentV2Status>;
}

/**
 * Check if a given object implements the StorageV2Status interface.
 */
export function instanceOfStorageV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "storageClassId" in value;
    isInstance = isInstance && "regionId" in value;

    return isInstance;
}

export function StorageV2StatusFromJSON(json: any): StorageV2Status {
    return StorageV2StatusFromJSONTyped(json, false);
}

export function StorageV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'storageClassId': json['storageClassId'],
        'regionId': json['regionId'],
        'usage': !exists(json, 'usage') ? undefined : StorageUsageV2StatusFromJSON(json['usage']),
        'attachments': !exists(json, 'attachments') ? undefined : ((json['attachments'] as Array<any>).map(StorageAttachmentV2StatusFromJSON)),
    };
}

export function StorageV2StatusToJSON(value?: StorageV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'storageClassId': value.storageClassId,
        'regionId': value.regionId,
        'usage': StorageUsageV2StatusToJSON(value.usage),
        'attachments': value.attachments === undefined ? undefined : ((value.attachments as Array<any>).map(StorageAttachmentV2StatusToJSON)),
    };
}

