/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { StorageV2CreateSpec } from './StorageV2CreateSpec';
import {
    StorageV2CreateSpecFromJSON,
    StorageV2CreateSpecFromJSONTyped,
    StorageV2CreateSpecToJSON,
} from './StorageV2CreateSpec';

/**
 * A storage create request.
 * @export
 * @interface StorageV2Create
 */
export interface StorageV2Create {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof StorageV2Create
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {StorageV2CreateSpec}
     * @memberof StorageV2Create
     */
    spec: StorageV2CreateSpec;
}

/**
 * Check if a given object implements the StorageV2Create interface.
 */
export function instanceOfStorageV2Create(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function StorageV2CreateFromJSON(json: any): StorageV2Create {
    return StorageV2CreateFromJSONTyped(json, false);
}

export function StorageV2CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2Create {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': StorageV2CreateSpecFromJSON(json['spec']),
    };
}

export function StorageV2CreateToJSON(value?: StorageV2Create | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': StorageV2CreateSpecToJSON(value.spec),
    };
}

