/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NFSV2Spec } from './NFSV2Spec';
import {
    NFSV2SpecFromJSON,
    NFSV2SpecFromJSONTyped,
    NFSV2SpecToJSON,
} from './NFSV2Spec';

/**
 * A storage's type
 * @export
 * @interface StorageTypeV2Spec
 */
export interface StorageTypeV2Spec {
    /**
     * 
     * @type {NFSV2Spec}
     * @memberof StorageTypeV2Spec
     */
    nFS?: NFSV2Spec;
}

/**
 * Check if a given object implements the StorageTypeV2Spec interface.
 */
export function instanceOfStorageTypeV2Spec(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageTypeV2SpecFromJSON(json: any): StorageTypeV2Spec {
    return StorageTypeV2SpecFromJSONTyped(json, false);
}

export function StorageTypeV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageTypeV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nFS': !exists(json, 'NFS') ? undefined : NFSV2SpecFromJSON(json['NFS']),
    };
}

export function StorageTypeV2SpecToJSON(value?: StorageTypeV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NFS': NFSV2SpecToJSON(value.nFS),
    };
}

