/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the usage of the storage
 * @export
 * @interface StorageUsageV2Status
 */
export interface StorageUsageV2Status {
    /**
     * total space allotted
     * @type {number}
     * @memberof StorageUsageV2Status
     */
    capacityGiB: number;
    /**
     * amount of storage space used
     * @type {number}
     * @memberof StorageUsageV2Status
     */
    usedGiB?: number;
    /**
     * amount of storage space free to use
     * @type {number}
     * @memberof StorageUsageV2Status
     */
    freeGiB?: number;
}

/**
 * Check if a given object implements the StorageUsageV2Status interface.
 */
export function instanceOfStorageUsageV2Status(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "capacityGiB" in value;

    return isInstance;
}

export function StorageUsageV2StatusFromJSON(json: any): StorageUsageV2Status {
    return StorageUsageV2StatusFromJSONTyped(json, false);
}

export function StorageUsageV2StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUsageV2Status {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacityGiB': json['capacityGiB'],
        'usedGiB': !exists(json, 'usedGiB') ? undefined : json['usedGiB'],
        'freeGiB': !exists(json, 'freeGiB') ? undefined : json['freeGiB'],
    };
}

export function StorageUsageV2StatusToJSON(value?: StorageUsageV2Status | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacityGiB': value.capacityGiB,
        'usedGiB': value.usedGiB,
        'freeGiB': value.freeGiB,
    };
}

