/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageAttachmentV2Spec } from './StorageAttachmentV2Spec';
import {
    StorageAttachmentV2SpecFromJSON,
    StorageAttachmentV2SpecFromJSONTyped,
    StorageAttachmentV2SpecToJSON,
} from './StorageAttachmentV2Spec';
import type { StorageTypeV2Spec } from './StorageTypeV2Spec';
import {
    StorageTypeV2SpecFromJSON,
    StorageTypeV2SpecFromJSONTyped,
    StorageTypeV2SpecToJSON,
} from './StorageTypeV2Spec';

/**
 * 
 * @export
 * @interface StorageV2CreateSpec
 */
export interface StorageV2CreateSpec {
    /**
     * Size of the storage
     * @type {string}
     * @memberof StorageV2CreateSpec
     */
    size: string;
    /**
     * 
     * @type {StorageTypeV2Spec}
     * @memberof StorageV2CreateSpec
     */
    storageType: StorageTypeV2Spec;
    /**
     * 
     * @type {StorageAttachmentV2Spec}
     * @memberof StorageV2CreateSpec
     */
    attachments?: StorageAttachmentV2Spec;
    /**
     * The storage class ID to provision the storage into.
     * @type {string}
     * @memberof StorageV2CreateSpec
     */
    storageClassId: string;
    /**
     * The organization to provision the resource in.
     * @type {string}
     * @memberof StorageV2CreateSpec
     */
    organizationId: string;
    /**
     * The region ID to provision the storage into.
     * @type {string}
     * @memberof StorageV2CreateSpec
     */
    regionId: string;
    /**
     * The project to provision the resource in.
     * @type {string}
     * @memberof StorageV2CreateSpec
     */
    projectId: string;
}

/**
 * Check if a given object implements the StorageV2CreateSpec interface.
 */
export function instanceOfStorageV2CreateSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "storageType" in value;
    isInstance = isInstance && "storageClassId" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function StorageV2CreateSpecFromJSON(json: any): StorageV2CreateSpec {
    return StorageV2CreateSpecFromJSONTyped(json, false);
}

export function StorageV2CreateSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2CreateSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'storageType': StorageTypeV2SpecFromJSON(json['storageType']),
        'attachments': !exists(json, 'attachments') ? undefined : StorageAttachmentV2SpecFromJSON(json['attachments']),
        'storageClassId': json['storageClassId'],
        'organizationId': json['organizationId'],
        'regionId': json['regionId'],
        'projectId': json['projectId'],
    };
}

export function StorageV2CreateSpecToJSON(value?: StorageV2CreateSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'storageType': StorageTypeV2SpecToJSON(value.storageType),
        'attachments': StorageAttachmentV2SpecToJSON(value.attachments),
        'storageClassId': value.storageClassId,
        'organizationId': value.organizationId,
        'regionId': value.regionId,
        'projectId': value.projectId,
    };
}

