/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceProvisioningStatus } from './ResourceProvisioningStatus';
import {
    ResourceProvisioningStatusFromJSON,
    ResourceProvisioningStatusFromJSONTyped,
    ResourceProvisioningStatusToJSON,
} from './ResourceProvisioningStatus';

/**
 * 
 * @export
 * @interface StorageAttachmentV2StatusNetworkIdsInner
 */
export interface StorageAttachmentV2StatusNetworkIdsInner {
    /**
     * 
     * @type {string}
     * @memberof StorageAttachmentV2StatusNetworkIdsInner
     */
    id?: string;
    /**
     * 
     * @type {ResourceProvisioningStatus}
     * @memberof StorageAttachmentV2StatusNetworkIdsInner
     */
    provisioningStatus?: ResourceProvisioningStatus;
}

/**
 * Check if a given object implements the StorageAttachmentV2StatusNetworkIdsInner interface.
 */
export function instanceOfStorageAttachmentV2StatusNetworkIdsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageAttachmentV2StatusNetworkIdsInnerFromJSON(json: any): StorageAttachmentV2StatusNetworkIdsInner {
    return StorageAttachmentV2StatusNetworkIdsInnerFromJSONTyped(json, false);
}

export function StorageAttachmentV2StatusNetworkIdsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAttachmentV2StatusNetworkIdsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'provisioningStatus': !exists(json, 'provisioningStatus') ? undefined : ResourceProvisioningStatusFromJSON(json['provisioningStatus']),
    };
}

export function StorageAttachmentV2StatusNetworkIdsInnerToJSON(value?: StorageAttachmentV2StatusNetworkIdsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'provisioningStatus': ResourceProvisioningStatusToJSON(value.provisioningStatus),
    };
}

