/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageAttachmentV2Spec } from './StorageAttachmentV2Spec';
import {
    StorageAttachmentV2SpecFromJSON,
    StorageAttachmentV2SpecFromJSONTyped,
    StorageAttachmentV2SpecToJSON,
} from './StorageAttachmentV2Spec';
import type { StorageTypeV2Spec } from './StorageTypeV2Spec';
import {
    StorageTypeV2SpecFromJSON,
    StorageTypeV2SpecFromJSONTyped,
    StorageTypeV2SpecToJSON,
} from './StorageTypeV2Spec';

/**
 * A storage's specification.
 * @export
 * @interface StorageV2Spec
 */
export interface StorageV2Spec {
    /**
     * size of the storage
     * @type {string}
     * @memberof StorageV2Spec
     */
    size: string;
    /**
     * 
     * @type {StorageTypeV2Spec}
     * @memberof StorageV2Spec
     */
    storageType: StorageTypeV2Spec;
    /**
     * 
     * @type {StorageAttachmentV2Spec}
     * @memberof StorageV2Spec
     */
    attachments?: StorageAttachmentV2Spec;
}

/**
 * Check if a given object implements the StorageV2Spec interface.
 */
export function instanceOfStorageV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "storageType" in value;

    return isInstance;
}

export function StorageV2SpecFromJSON(json: any): StorageV2Spec {
    return StorageV2SpecFromJSONTyped(json, false);
}

export function StorageV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'storageType': StorageTypeV2SpecFromJSON(json['storageType']),
        'attachments': !exists(json, 'attachments') ? undefined : StorageAttachmentV2SpecFromJSON(json['attachments']),
    };
}

export function StorageV2SpecToJSON(value?: StorageV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'storageType': StorageTypeV2SpecToJSON(value.storageType),
        'attachments': StorageAttachmentV2SpecToJSON(value.attachments),
    };
}

