/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { StorageV2Spec } from './StorageV2Spec';
import {
    StorageV2SpecFromJSON,
    StorageV2SpecFromJSONTyped,
    StorageV2SpecToJSON,
} from './StorageV2Spec';

/**
 * A storage create request.
 * @export
 * @interface StorageV2Update
 */
export interface StorageV2Update {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof StorageV2Update
     */
    metadata: ResourceWriteMetadata;
    /**
     * 
     * @type {StorageV2Spec}
     * @memberof StorageV2Update
     */
    spec: StorageV2Spec;
}

/**
 * Check if a given object implements the StorageV2Update interface.
 */
export function instanceOfStorageV2Update(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function StorageV2UpdateFromJSON(json: any): StorageV2Update {
    return StorageV2UpdateFromJSONTyped(json, false);
}

export function StorageV2UpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageV2Update {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': StorageV2SpecFromJSON(json['spec']),
    };
}

export function StorageV2UpdateToJSON(value?: StorageV2Update | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': StorageV2SpecToJSON(value.spec),
    };
}

