/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the usage of the storage
 * @export
 * @interface StorageUsageV2Spec
 */
export interface StorageUsageV2Spec {
    /**
     * total space allotted
     * @type {string}
     * @memberof StorageUsageV2Spec
     */
    capacity: string;
    /**
     * amount of storage space utilizied
     * @type {string}
     * @memberof StorageUsageV2Spec
     */
    used?: string;
    /**
     * amount of storage space free to utilize
     * @type {string}
     * @memberof StorageUsageV2Spec
     */
    free?: string;
}

/**
 * Check if a given object implements the StorageUsageV2Spec interface.
 */
export function instanceOfStorageUsageV2Spec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "capacity" in value;

    return isInstance;
}

export function StorageUsageV2SpecFromJSON(json: any): StorageUsageV2Spec {
    return StorageUsageV2SpecFromJSONTyped(json, false);
}

export function StorageUsageV2SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUsageV2Spec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacity': json['capacity'],
        'used': !exists(json, 'used') ? undefined : json['used'],
        'free': !exists(json, 'free') ? undefined : json['free'],
    };
}

export function StorageUsageV2SpecToJSON(value?: StorageUsageV2Spec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacity': value.capacity,
        'used': value.used,
        'free': value.free,
    };
}

