/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StaticResourceMetadata } from './StaticResourceMetadata';
import {
	StaticResourceMetadataFromJSON,
	StaticResourceMetadataFromJSONTyped,
	StaticResourceMetadataToJSON
} from './StaticResourceMetadata';
import type { VolumeClassV2Spec } from './VolumeClassV2Spec';
import {
	VolumeClassV2SpecFromJSON,
	VolumeClassV2SpecFromJSONTyped,
	VolumeClassV2SpecToJSON
} from './VolumeClassV2Spec';

/**
 * A provider-neutral block-storage volume class available in a Region.
 * @export
 * @interface VolumeClassV2Read
 */
export interface VolumeClassV2Read {
	/**
	 *
	 * @type {StaticResourceMetadata}
	 * @memberof VolumeClassV2Read
	 */
	metadata: StaticResourceMetadata;
	/**
	 *
	 * @type {VolumeClassV2Spec}
	 * @memberof VolumeClassV2Read
	 */
	spec: VolumeClassV2Spec;
}

/**
 * Check if a given object implements the VolumeClassV2Read interface.
 */
export function instanceOfVolumeClassV2Read(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'metadata' in value;
	isInstance = isInstance && 'spec' in value;

	return isInstance;
}

export function VolumeClassV2ReadFromJSON(json: any): VolumeClassV2Read {
	return VolumeClassV2ReadFromJSONTyped(json, false);
}

export function VolumeClassV2ReadFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): VolumeClassV2Read {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		metadata: StaticResourceMetadataFromJSON(json['metadata']),
		spec: VolumeClassV2SpecFromJSON(json['spec'])
	};
}

export function VolumeClassV2ReadToJSON(value?: VolumeClassV2Read | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		metadata: StaticResourceMetadataToJSON(value.metadata),
		spec: VolumeClassV2SpecToJSON(value.spec)
	};
}
