/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
	ProjectScopedResourceReadMetadataFromJSON,
	ProjectScopedResourceReadMetadataFromJSONTyped,
	ProjectScopedResourceReadMetadataToJSON
} from './ProjectScopedResourceReadMetadata';
import type { VolumeV2Spec } from './VolumeV2Spec';
import {
	VolumeV2SpecFromJSON,
	VolumeV2SpecFromJSONTyped,
	VolumeV2SpecToJSON
} from './VolumeV2Spec';
import type { VolumeV2Status } from './VolumeV2Status';
import {
	VolumeV2StatusFromJSON,
	VolumeV2StatusFromJSONTyped,
	VolumeV2StatusToJSON
} from './VolumeV2Status';

/**
 * A block storage volume.
 * @export
 * @interface VolumeV2Read
 */
export interface VolumeV2Read {
	/**
	 *
	 * @type {ProjectScopedResourceReadMetadata}
	 * @memberof VolumeV2Read
	 */
	metadata: ProjectScopedResourceReadMetadata;
	/**
	 *
	 * @type {VolumeV2Spec}
	 * @memberof VolumeV2Read
	 */
	spec: VolumeV2Spec;
	/**
	 *
	 * @type {VolumeV2Status}
	 * @memberof VolumeV2Read
	 */
	status: VolumeV2Status;
}

/**
 * Check if a given object implements the VolumeV2Read interface.
 */
export function instanceOfVolumeV2Read(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'metadata' in value;
	isInstance = isInstance && 'spec' in value;
	isInstance = isInstance && 'status' in value;

	return isInstance;
}

export function VolumeV2ReadFromJSON(json: any): VolumeV2Read {
	return VolumeV2ReadFromJSONTyped(json, false);
}

export function VolumeV2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeV2Read {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		metadata: ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
		spec: VolumeV2SpecFromJSON(json['spec']),
		status: VolumeV2StatusFromJSON(json['status'])
	};
}

export function VolumeV2ReadToJSON(value?: VolumeV2Read | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		metadata: ProjectScopedResourceReadMetadataToJSON(value.metadata),
		spec: VolumeV2SpecToJSON(value.spec),
		status: VolumeV2StatusToJSON(value.status)
	};
}
