/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Custom claims for authorisation, specific to UNI
 * @export
 * @interface AuthClaims
 */
export interface AuthClaims {
    /**
     * Denotes the type of account represented. This is non-standard claim.
     * @type {string}
     * @memberof AuthClaims
     */
    acctype: AuthClaimsAcctypeEnum;
    /**
     * The IDs of organisations of which the account is a member. This may be just the org for which
     * they are currently authenticated.
     * 
     * @type {Array<string>}
     * @memberof AuthClaims
     */
    orgIds: Array<string>;
}


/**
 * @export
 */
export const AuthClaimsAcctypeEnum = {
    System: 'system',
    Service: 'service',
    User: 'user'
} as const;
export type AuthClaimsAcctypeEnum = typeof AuthClaimsAcctypeEnum[keyof typeof AuthClaimsAcctypeEnum];


/**
 * Check if a given object implements the AuthClaims interface.
 */
export function instanceOfAuthClaims(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "acctype" in value;
    isInstance = isInstance && "orgIds" in value;

    return isInstance;
}

export function AuthClaimsFromJSON(json: any): AuthClaims {
    return AuthClaimsFromJSONTyped(json, false);
}

export function AuthClaimsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthClaims {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'acctype': json['acctype'],
        'orgIds': json['orgIds'],
    };
}

export function AuthClaimsToJSON(value?: AuthClaims | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'acctype': value.acctype,
        'orgIds': value.orgIds,
    };
}

