apiVersion: v2
name: unikorn-ui
description: A Helm chart for deploying Unikorn UI

type: application

# sentinel: patched at release time by release.yaml; overridden by --version for nightly builds
version: 0.0.0
appVersion: 0.0.0

icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: 0.1.17
  repository: https://nscaledev.github.io/uni-helm-common
