# Set the global container repo.
repository: ghcr.io

# Set the global container repo organization.
organization: unikorn-cloud

# Set the global container tag.
# Defaults to the chart revision, which should be in lock-step with the
# actual release.
# tag:

# Set the docker configuration, doing so will create a secret and link it
# to the service accounts of all the controllers.  You can do something like:
# --set dockerConfig=$(cat ~/.docker/config.json | base64 -w0)
dockerConfig:

# Set the image pull secret on the service accounts of all the controllers.
# This is an alternative to dockerConfigs, but unlikely to play ball with
# ArgoCD as it's a foreign object that needs pruning.
imagePullSecret:

# Allows override of the global default image.
image:

# What DNS name I have.
host: console.unikorn-cloud.org

# Backend API configuration.
api:
  # The API's hostname.
  host: https://api.unikorn-cloud.org

region:
  # The API's hostname.
  host: https://region.unikorn-cloud.org

# Authentication settings.
oauth2:
  # The identity provider's name (and OIDC discovery endpoint).
  issuer: https://identity.unikorn-cloud.org
  # The client identifier assigned to this application.
  clientID: 3fc34852-9186-4884-b580-78bf4bcf628a

ingress:
  # Sets the ingress class to use.
  class: ~
  # Cert Manager certificate issuer to use.  If not specified it will generate a self signed one.
  issuer: ~
  # clusterIssuer to use.
  clusterIssuer: ~
  # If true, will add the external DNS hostname annotation.
  externalDns: false
