apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-ui
  labels:
    {{- include "unikorn-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-ui
  template:
    metadata:
      labels:
        app: unikorn-ui
    spec:
      containers:
      - name: unikorn-ui
        image: {{ include "unikorn-ui.image" . }}
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PUBLIC_APPLICATION_VERSION
          value: {{ .Chart.Version }}
        - name: PUBLIC_KUBERNETES_HOST
          value: {{ .Values.kubernetes.host }}
        - name: PUBLIC_REGION_HOST
          value: {{ .Values.region.host }}
        - name: PUBLIC_OAUTH2_ISSUER
          value: {{ .Values.identity.host }}
        # TODO: implement OIDC discovery protocol.
        - name: PUBLIC_OAUTH2_AUTHORIZATION_ENDPOINT
          value: {{ .Values.identity.host }}/oauth2/v2/authorization
        - name: PUBLIC_OAUTH2_TOKEN_ENDPOINT
          value: {{ .Values.identity.host }}/oauth2/v2/token
        - name: PUBLIC_OAUTH2_JWKS_ENDPOINT
          value: {{ .Values.identity.host }}/oauth2/v2/jwks
        - name: PUBLIC_OAUTH2_CLIENT_ID
          value: {{ .Values.oauth2.clientID }}
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-ui
      securityContext:
        runAsNonRoot: true
