{{- if not .Values.oauth2.clientSecretSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: unikorn-ui-oidc-secret
type: Opaque
data:
  OIDC_CLIENT_ID: {{ b64enc .Values.oauth2.clientID }}
  OIDC_CLIENT_SECRET: {{ b64enc .Values.oauth2.clientSecret }}
{{- end }}
