apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-ui
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
{{- with ( include "unikorn-ui.imagePullSecrets" . ) }}
imagePullSecrets:
{{ . }}
{{- end }}
