/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConsoleOutput,
  ConsoleSession,
  Image,
  InstanceCreate,
  InstanceRead,
  InstanceSnapshotCreate,
  InstanceUpdate,
  ModelError,
  SshKey,
} from '../models/index';
import {
    ConsoleOutputFromJSON,
    ConsoleOutputToJSON,
    ConsoleSessionFromJSON,
    ConsoleSessionToJSON,
    ImageFromJSON,
    ImageToJSON,
    InstanceCreateFromJSON,
    InstanceCreateToJSON,
    InstanceReadFromJSON,
    InstanceReadToJSON,
    InstanceSnapshotCreateFromJSON,
    InstanceSnapshotCreateToJSON,
    InstanceUpdateFromJSON,
    InstanceUpdateToJSON,
    ModelErrorFromJSON,
    ModelErrorToJSON,
    SshKeyFromJSON,
    SshKeyToJSON,
} from '../models/index';

export interface ApiV2InstancesGetRequest {
    tag?: Array<string>;
    organizationID?: Array<string>;
    projectID?: Array<string>;
    regionID?: Array<string>;
    networkID?: Array<string>;
}

export interface ApiV2InstancesInstanceIDConsoleoutputGetRequest {
    instanceID: string;
    length?: number;
}

export interface ApiV2InstancesInstanceIDConsolesessionGetRequest {
    instanceID: string;
}

export interface ApiV2InstancesInstanceIDDeleteRequest {
    instanceID: string;
}

export interface ApiV2InstancesInstanceIDGetRequest {
    instanceID: string;
}

export interface ApiV2InstancesInstanceIDPutRequest {
    instanceID: string;
    instanceUpdate: InstanceUpdate;
}

export interface ApiV2InstancesInstanceIDRebootPostRequest {
    instanceID: string;
    hard?: boolean;
}

export interface ApiV2InstancesInstanceIDSnapshotPostRequest {
    instanceID: string;
    instanceSnapshotCreate: InstanceSnapshotCreate;
}

export interface ApiV2InstancesInstanceIDSshkeyGetRequest {
    instanceID: string;
}

export interface ApiV2InstancesInstanceIDStartPostRequest {
    instanceID: string;
}

export interface ApiV2InstancesInstanceIDStopPostRequest {
    instanceID: string;
}

export interface ApiV2InstancesPostRequest {
    instanceCreate: InstanceCreate;
}

/**
 * 
 */
export class InstancesApi extends runtime.BaseAPI {

    /**
     * List compute instances.
     * List instances
     */
    async apiV2InstancesGetRaw(requestParameters: ApiV2InstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InstanceRead>>> {
        const queryParameters: any = {};

        if (requestParameters.tag) {
            queryParameters['tag'] = requestParameters.tag.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.organizationID) {
            queryParameters['organizationID'] = requestParameters.organizationID;
        }

        if (requestParameters.projectID) {
            queryParameters['projectID'] = requestParameters.projectID;
        }

        if (requestParameters.regionID) {
            queryParameters['regionID'] = requestParameters.regionID;
        }

        if (requestParameters.networkID) {
            queryParameters['networkID'] = requestParameters.networkID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InstanceReadFromJSON));
    }

    /**
     * List compute instances.
     * List instances
     */
    async apiV2InstancesGet(requestParameters: ApiV2InstancesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InstanceRead>> {
        const response = await this.apiV2InstancesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the console output for an instance.
     * Get instance console output
     */
    async apiV2InstancesInstanceIDConsoleoutputGetRaw(requestParameters: ApiV2InstancesInstanceIDConsoleoutputGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleOutput>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDConsoleoutputGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.length !== undefined) {
            queryParameters['length'] = requestParameters.length;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/consoleoutput`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleOutputFromJSON(jsonValue));
    }

    /**
     * Get the console output for an instance.
     * Get instance console output
     */
    async apiV2InstancesInstanceIDConsoleoutputGet(requestParameters: ApiV2InstancesInstanceIDConsoleoutputGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleOutput> {
        const response = await this.apiV2InstancesInstanceIDConsoleoutputGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new console session for an instance.
     * Get instance console VNC
     */
    async apiV2InstancesInstanceIDConsolesessionGetRaw(requestParameters: ApiV2InstancesInstanceIDConsolesessionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleSession>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDConsolesessionGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/consolesession`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleSessionFromJSON(jsonValue));
    }

    /**
     * Create a new console session for an instance.
     * Get instance console VNC
     */
    async apiV2InstancesInstanceIDConsolesessionGet(requestParameters: ApiV2InstancesInstanceIDConsolesessionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleSession> {
        const response = await this.apiV2InstancesInstanceIDConsolesessionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an instance.
     * Delete instance
     */
    async apiV2InstancesInstanceIDDeleteRaw(requestParameters: ApiV2InstancesInstanceIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an instance.
     * Delete instance
     */
    async apiV2InstancesInstanceIDDelete(requestParameters: ApiV2InstancesInstanceIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2InstancesInstanceIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get an instance.
     * Get instance
     */
    async apiV2InstancesInstanceIDGetRaw(requestParameters: ApiV2InstancesInstanceIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceRead>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceReadFromJSON(jsonValue));
    }

    /**
     * Get an instance.
     * Get instance
     */
    async apiV2InstancesInstanceIDGet(requestParameters: ApiV2InstancesInstanceIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceRead> {
        const response = await this.apiV2InstancesInstanceIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an instance.
     * Update instance
     */
    async apiV2InstancesInstanceIDPutRaw(requestParameters: ApiV2InstancesInstanceIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceRead>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDPut.');
        }

        if (requestParameters.instanceUpdate === null || requestParameters.instanceUpdate === undefined) {
            throw new runtime.RequiredError('instanceUpdate','Required parameter requestParameters.instanceUpdate was null or undefined when calling apiV2InstancesInstanceIDPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InstanceUpdateToJSON(requestParameters.instanceUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceReadFromJSON(jsonValue));
    }

    /**
     * Update an instance.
     * Update instance
     */
    async apiV2InstancesInstanceIDPut(requestParameters: ApiV2InstancesInstanceIDPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceRead> {
        const response = await this.apiV2InstancesInstanceIDPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reboot an instance.  By default this will perform a software ACPI reboot. You can specifiy a hard power cycle as a query parameter.
     * Reboot instance
     */
    async apiV2InstancesInstanceIDRebootPostRaw(requestParameters: ApiV2InstancesInstanceIDRebootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDRebootPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.hard !== undefined) {
            queryParameters['hard'] = requestParameters.hard;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/reboot`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reboot an instance.  By default this will perform a software ACPI reboot. You can specifiy a hard power cycle as a query parameter.
     * Reboot instance
     */
    async apiV2InstancesInstanceIDRebootPost(requestParameters: ApiV2InstancesInstanceIDRebootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2InstancesInstanceIDRebootPostRaw(requestParameters, initOverrides);
    }

    /**
     * Take a snapshot of an instance and create an image from it.
     * Snapshot instance
     */
    async apiV2InstancesInstanceIDSnapshotPostRaw(requestParameters: ApiV2InstancesInstanceIDSnapshotPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDSnapshotPost.');
        }

        if (requestParameters.instanceSnapshotCreate === null || requestParameters.instanceSnapshotCreate === undefined) {
            throw new runtime.RequiredError('instanceSnapshotCreate','Required parameter requestParameters.instanceSnapshotCreate was null or undefined when calling apiV2InstancesInstanceIDSnapshotPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/snapshot`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InstanceSnapshotCreateToJSON(requestParameters.instanceSnapshotCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Take a snapshot of an instance and create an image from it.
     * Snapshot instance
     */
    async apiV2InstancesInstanceIDSnapshotPost(requestParameters: ApiV2InstancesInstanceIDSnapshotPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.apiV2InstancesInstanceIDSnapshotPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the SSH key for an instance.
     * Get instance SSH key
     */
    async apiV2InstancesInstanceIDSshkeyGetRaw(requestParameters: ApiV2InstancesInstanceIDSshkeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SshKey>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDSshkeyGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/sshkey`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SshKeyFromJSON(jsonValue));
    }

    /**
     * Retrieve the SSH key for an instance.
     * Get instance SSH key
     */
    async apiV2InstancesInstanceIDSshkeyGet(requestParameters: ApiV2InstancesInstanceIDSshkeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SshKey> {
        const response = await this.apiV2InstancesInstanceIDSshkeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a stopped instance.
     * Start instance
     */
    async apiV2InstancesInstanceIDStartPostRaw(requestParameters: ApiV2InstancesInstanceIDStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDStartPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/start`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start a stopped instance.
     * Start instance
     */
    async apiV2InstancesInstanceIDStartPost(requestParameters: ApiV2InstancesInstanceIDStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2InstancesInstanceIDStartPostRaw(requestParameters, initOverrides);
    }

    /**
     * Stop a running instnace.
     * Stop instance
     */
    async apiV2InstancesInstanceIDStopPostRaw(requestParameters: ApiV2InstancesInstanceIDStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.instanceID === null || requestParameters.instanceID === undefined) {
            throw new runtime.RequiredError('instanceID','Required parameter requestParameters.instanceID was null or undefined when calling apiV2InstancesInstanceIDStopPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances/{instanceID}/stop`.replace(`{${"instanceID"}}`, encodeURIComponent(String(requestParameters.instanceID))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop a running instnace.
     * Stop instance
     */
    async apiV2InstancesInstanceIDStopPost(requestParameters: ApiV2InstancesInstanceIDStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV2InstancesInstanceIDStopPostRaw(requestParameters, initOverrides);
    }

    /**
     * Create an instance.
     * Create instance
     */
    async apiV2InstancesPostRaw(requestParameters: ApiV2InstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceRead>> {
        if (requestParameters.instanceCreate === null || requestParameters.instanceCreate === undefined) {
            throw new runtime.RequiredError('instanceCreate','Required parameter requestParameters.instanceCreate was null or undefined when calling apiV2InstancesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v2/instances`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InstanceCreateToJSON(requestParameters.instanceCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceReadFromJSON(jsonValue));
    }

    /**
     * Create an instance.
     * Create instance
     */
    async apiV2InstancesPost(requestParameters: ApiV2InstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceRead> {
        const response = await this.apiV2InstancesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
